/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.tea;

import fr.univcotedazur.polytech.si4.fsm.project.ITimer;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public class TeaStatemachine implements ITeaStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private List<SCInterfaceListener> listeners = new LinkedList<SCInterfaceListener>();
		
		public List<SCInterfaceListener> getListeners() {
			return listeners;
		}
		private boolean teaBagDropped;
		
		
		public void raiseTeaBagDropped() {
			synchronized(TeaStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							teaBagDropped = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean isInfused;
		
		
		public void raiseIsInfused() {
			synchronized(TeaStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							isInfused = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean isHot;
		
		
		public void raiseIsHot() {
			synchronized(TeaStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							isHot = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean sugarFinishPoored;
		
		
		public void raiseSugarFinishPoored() {
			synchronized(TeaStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							sugarFinishPoored = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean drinkFinishPoored;
		
		
		public void raiseDrinkFinishPoored() {
			synchronized(TeaStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							drinkFinishPoored = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean drinkPickedUp;
		
		
		public void raiseDrinkPickedUp() {
			synchronized(TeaStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							drinkPickedUp = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean prepare;
		
		
		public void raisePrepare() {
			synchronized(TeaStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							prepare = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean placeTeaBag;
		
		
		public boolean isRaisedPlaceTeaBag() {
			synchronized(TeaStatemachine.this) {
				return placeTeaBag;
			}
		}
		
		protected void raisePlaceTeaBag() {
			synchronized(TeaStatemachine.this) {
				placeTeaBag = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPlaceTeaBagRaised();
				}
			}
		}
		
		private boolean placeCup;
		
		
		public boolean isRaisedPlaceCup() {
			synchronized(TeaStatemachine.this) {
				return placeCup;
			}
		}
		
		protected void raisePlaceCup() {
			synchronized(TeaStatemachine.this) {
				placeCup = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPlaceCupRaised();
				}
			}
		}
		
		private boolean heating;
		
		
		public boolean isRaisedHeating() {
			synchronized(TeaStatemachine.this) {
				return heating;
			}
		}
		
		protected void raiseHeating() {
			synchronized(TeaStatemachine.this) {
				heating = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onHeatingRaised();
				}
			}
		}
		
		private boolean pooringSugar;
		
		
		public boolean isRaisedPooringSugar() {
			synchronized(TeaStatemachine.this) {
				return pooringSugar;
			}
		}
		
		protected void raisePooringSugar() {
			synchronized(TeaStatemachine.this) {
				pooringSugar = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPooringSugarRaised();
				}
			}
		}
		
		private boolean pooringDrink;
		
		
		public boolean isRaisedPooringDrink() {
			synchronized(TeaStatemachine.this) {
				return pooringDrink;
			}
		}
		
		protected void raisePooringDrink() {
			synchronized(TeaStatemachine.this) {
				pooringDrink = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPooringDrinkRaised();
				}
			}
		}
		
		private boolean preparationFinished;
		
		
		public boolean isRaisedPreparationFinished() {
			synchronized(TeaStatemachine.this) {
				return preparationFinished;
			}
		}
		
		protected void raisePreparationFinished() {
			synchronized(TeaStatemachine.this) {
				preparationFinished = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPreparationFinishedRaised();
				}
			}
		}
		
		private boolean brewing;
		
		
		public boolean isRaisedBrewing() {
			synchronized(TeaStatemachine.this) {
				return brewing;
			}
		}
		
		protected void raiseBrewing() {
			synchronized(TeaStatemachine.this) {
				brewing = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onBrewingRaised();
				}
			}
		}
		
		private boolean dropTeaBag;
		
		
		public boolean isRaisedDropTeaBag() {
			synchronized(TeaStatemachine.this) {
				return dropTeaBag;
			}
		}
		
		protected void raiseDropTeaBag() {
			synchronized(TeaStatemachine.this) {
				dropTeaBag = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDropTeaBagRaised();
				}
			}
		}
		
		protected void clearEvents() {
			teaBagDropped = false;
			isInfused = false;
			isHot = false;
			sugarFinishPoored = false;
			drinkFinishPoored = false;
			drinkPickedUp = false;
			prepare = false;
		}
		protected void clearOutEvents() {
		
		placeTeaBag = false;
		placeCup = false;
		heating = false;
		pooringSugar = false;
		pooringDrink = false;
		preparationFinished = false;
		brewing = false;
		dropTeaBag = false;
		}
		
	}
	
	
	protected SCInterfaceImpl sCInterface;
	
	private boolean initialized = false;
	
	public enum State {
		main_region_prepareIngredient,
		main_region_prepareIngredient_r1_positionningCup,
		main_region_prepareIngredient_r1_getTeaBag,
		main_region_prepareIngredient_r1_cupPositionned,
		main_region_prepareIngredient_r2_Heating,
		main_region_prepareIngredient_r2_IsHot,
		main_region_poorIngredient,
		main_region_poorIngredient_r1_poorSugar,
		main_region_poorIngredient_r1_sugarPoored,
		main_region_poorIngredient_r2_poorDrink,
		main_region_poorIngredient_r2_drinkPoored,
		main_region_DrinkDistribute,
		main_region__final_,
		main_region_brew,
		main_region_dropTeaBag,
		$NullState$
	};
	
	private final State[] stateVector = new State[2];
	
	private int nextStateIndex;
	
	private ITimer timer;
	
	private final boolean[] timeEvents = new boolean[6];
	
	private BlockingQueue<Runnable> inEventQueue = new LinkedBlockingQueue<Runnable>();
	private boolean isRunningCycle = false;
	public TeaStatemachine() {
		sCInterface = new SCInterfaceImpl();
	}
	
	public synchronized void init() {
		this.initialized = true;
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		for (int i = 0; i < 2; i++) {
			stateVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
	}
	
	public synchronized void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		enterSequence_main_region_default();
	}
	
	public synchronized void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		
		if (isRunningCycle) {
			return;
		}
		isRunningCycle = true;
		
		clearOutEvents();
	
		Runnable task = getNextEvent();
		if (task == null) {
			task = getDefaultEvent();
		}
		
		while (task != null) {
			task.run();
			clearEvents();
			task = getNextEvent();
		}
		
		isRunningCycle = false;
	}
	
	protected synchronized void singleCycle() {
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case main_region_prepareIngredient_r1_positionningCup:
				main_region_prepareIngredient_r1_positionningCup_react(true);
				break;
			case main_region_prepareIngredient_r1_getTeaBag:
				main_region_prepareIngredient_r1_getTeaBag_react(true);
				break;
			case main_region_prepareIngredient_r1_cupPositionned:
				main_region_prepareIngredient_r1_cupPositionned_react(true);
				break;
			case main_region_prepareIngredient_r2_Heating:
				main_region_prepareIngredient_r2_Heating_react(true);
				break;
			case main_region_prepareIngredient_r2_IsHot:
				main_region_prepareIngredient_r2_IsHot_react(true);
				break;
			case main_region_poorIngredient_r1_poorSugar:
				main_region_poorIngredient_r1_poorSugar_react(true);
				break;
			case main_region_poorIngredient_r1_sugarPoored:
				main_region_poorIngredient_r1_sugarPoored_react(true);
				break;
			case main_region_poorIngredient_r2_poorDrink:
				main_region_poorIngredient_r2_poorDrink_react(true);
				break;
			case main_region_poorIngredient_r2_drinkPoored:
				main_region_poorIngredient_r2_drinkPoored_react(true);
				break;
			case main_region_DrinkDistribute:
				main_region_DrinkDistribute_react(true);
				break;
			case main_region__final_:
				main_region__final__react(true);
				break;
			case main_region_brew:
				main_region_brew_react(true);
				break;
			case main_region_dropTeaBag:
				main_region_dropTeaBag_react(true);
				break;
			default:
				// $NullState$
			}
		}
	}
	
	protected Runnable getNextEvent() {
		if(!inEventQueue.isEmpty()) {
			return inEventQueue.poll();
		}
		return null;
	}
	
	protected Runnable getDefaultEvent() {
		return new Runnable() {
			@Override
			public void run() {
				singleCycle();
			}
		};
	}
	
	public synchronized void exit() {
		exitSequence_main_region();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NullState$||stateVector[1] != State.$NullState$;
	}
	
	/** 
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return (stateVector[0] == State.main_region__final_) && (stateVector[1] == State.$NullState$);
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCInterface.clearEvents();
		for (int i=0; i<timeEvents.length; i++) {
			timeEvents[i] = false;
		}
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
		sCInterface.clearOutEvents();
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case main_region_prepareIngredient:
			return stateVector[0].ordinal() >= State.
					main_region_prepareIngredient.ordinal()&& stateVector[0].ordinal() <= State.main_region_prepareIngredient_r2_IsHot.ordinal();
		case main_region_prepareIngredient_r1_positionningCup:
			return stateVector[0] == State.main_region_prepareIngredient_r1_positionningCup;
		case main_region_prepareIngredient_r1_getTeaBag:
			return stateVector[0] == State.main_region_prepareIngredient_r1_getTeaBag;
		case main_region_prepareIngredient_r1_cupPositionned:
			return stateVector[0] == State.main_region_prepareIngredient_r1_cupPositionned;
		case main_region_prepareIngredient_r2_Heating:
			return stateVector[1] == State.main_region_prepareIngredient_r2_Heating;
		case main_region_prepareIngredient_r2_IsHot:
			return stateVector[1] == State.main_region_prepareIngredient_r2_IsHot;
		case main_region_poorIngredient:
			return stateVector[0].ordinal() >= State.
					main_region_poorIngredient.ordinal()&& stateVector[0].ordinal() <= State.main_region_poorIngredient_r2_drinkPoored.ordinal();
		case main_region_poorIngredient_r1_poorSugar:
			return stateVector[0] == State.main_region_poorIngredient_r1_poorSugar;
		case main_region_poorIngredient_r1_sugarPoored:
			return stateVector[0] == State.main_region_poorIngredient_r1_sugarPoored;
		case main_region_poorIngredient_r2_poorDrink:
			return stateVector[1] == State.main_region_poorIngredient_r2_poorDrink;
		case main_region_poorIngredient_r2_drinkPoored:
			return stateVector[1] == State.main_region_poorIngredient_r2_drinkPoored;
		case main_region_DrinkDistribute:
			return stateVector[0] == State.main_region_DrinkDistribute;
		case main_region__final_:
			return stateVector[0] == State.main_region__final_;
		case main_region_brew:
			return stateVector[0] == State.main_region_brew;
		case main_region_dropTeaBag:
			return stateVector[0] == State.main_region_dropTeaBag;
		default:
			return false;
		}
	}
	
	/**
	* Set the {@link ITimer} for the state machine. It must be set
	* externally on a timed state machine before a run cycle can be correctly
	* executed.
	* 
	* @param timer
	*/
	public synchronized void setTimer(ITimer timer) {
		this.timer = timer;
	}
	
	/**
	* Returns the currently used timer.
	* 
	* @return {@link ITimer}
	*/
	public ITimer getTimer() {
		return timer;
	}
	
	public synchronized void timeElapsed(int eventID) {
		inEventQueue.add(new Runnable() {
			@Override
			public void run() {
				timeEvents[eventID] = true;
				singleCycle();
			}
		});
		runCycle();
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	public synchronized void raiseTeaBagDropped() {
		sCInterface.raiseTeaBagDropped();
	}
	
	public synchronized void raiseIsInfused() {
		sCInterface.raiseIsInfused();
	}
	
	public synchronized void raiseIsHot() {
		sCInterface.raiseIsHot();
	}
	
	public synchronized void raiseSugarFinishPoored() {
		sCInterface.raiseSugarFinishPoored();
	}
	
	public synchronized void raiseDrinkFinishPoored() {
		sCInterface.raiseDrinkFinishPoored();
	}
	
	public synchronized void raiseDrinkPickedUp() {
		sCInterface.raiseDrinkPickedUp();
	}
	
	public synchronized void raisePrepare() {
		sCInterface.raisePrepare();
	}
	
	public synchronized boolean isRaisedPlaceTeaBag() {
		return sCInterface.isRaisedPlaceTeaBag();
	}
	
	public synchronized boolean isRaisedPlaceCup() {
		return sCInterface.isRaisedPlaceCup();
	}
	
	public synchronized boolean isRaisedHeating() {
		return sCInterface.isRaisedHeating();
	}
	
	public synchronized boolean isRaisedPooringSugar() {
		return sCInterface.isRaisedPooringSugar();
	}
	
	public synchronized boolean isRaisedPooringDrink() {
		return sCInterface.isRaisedPooringDrink();
	}
	
	public synchronized boolean isRaisedPreparationFinished() {
		return sCInterface.isRaisedPreparationFinished();
	}
	
	public synchronized boolean isRaisedBrewing() {
		return sCInterface.isRaisedBrewing();
	}
	
	public synchronized boolean isRaisedDropTeaBag() {
		return sCInterface.isRaisedDropTeaBag();
	}
	
	/* Entry action for state 'positionningCup'. */
	private void entryAction_main_region_prepareIngredient_r1_positionningCup() {
		timer.setTimer(this, 0, (2 * 1000), false);
		
		sCInterface.raisePlaceCup();
	}
	
	/* Entry action for state 'getTeaBag'. */
	private void entryAction_main_region_prepareIngredient_r1_getTeaBag() {
		timer.setTimer(this, 1, (1 * 1000), false);
		
		sCInterface.raisePlaceTeaBag();
	}
	
	/* Entry action for state 'IsHot'. */
	private void entryAction_main_region_prepareIngredient_r2_IsHot() {
		timer.setTimer(this, 2, 100, true);
	}
	
	/* Entry action for state 'poorSugar'. */
	private void entryAction_main_region_poorIngredient_r1_poorSugar() {
		sCInterface.raisePooringSugar();
	}
	
	/* Entry action for state 'poorDrink'. */
	private void entryAction_main_region_poorIngredient_r2_poorDrink() {
		sCInterface.raisePooringDrink();
	}
	
	/* Entry action for state 'drinkPoored'. */
	private void entryAction_main_region_poorIngredient_r2_drinkPoored() {
		timer.setTimer(this, 3, 100, true);
	}
	
	/* Entry action for state 'brew'. */
	private void entryAction_main_region_brew() {
		timer.setTimer(this, 4, (5 * 1000), false);
		
		sCInterface.raiseBrewing();
	}
	
	/* Entry action for state 'dropTeaBag'. */
	private void entryAction_main_region_dropTeaBag() {
		timer.setTimer(this, 5, (2 * 1000), false);
		
		sCInterface.raiseDropTeaBag();
	}
	
	/* Exit action for state 'positionningCup'. */
	private void exitAction_main_region_prepareIngredient_r1_positionningCup() {
		timer.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'getTeaBag'. */
	private void exitAction_main_region_prepareIngredient_r1_getTeaBag() {
		timer.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'IsHot'. */
	private void exitAction_main_region_prepareIngredient_r2_IsHot() {
		timer.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'drinkPoored'. */
	private void exitAction_main_region_poorIngredient_r2_drinkPoored() {
		timer.unsetTimer(this, 3);
	}
	
	/* Exit action for state 'brew'. */
	private void exitAction_main_region_brew() {
		timer.unsetTimer(this, 4);
	}
	
	/* Exit action for state 'dropTeaBag'. */
	private void exitAction_main_region_dropTeaBag() {
		timer.unsetTimer(this, 5);
	}
	
	/* 'default' enter sequence for state prepareIngredient */
	private void enterSequence_main_region_prepareIngredient_default() {
		enterSequence_main_region_prepareIngredient_r1_default();
		enterSequence_main_region_prepareIngredient_r2_default();
	}
	
	/* 'default' enter sequence for state positionningCup */
	private void enterSequence_main_region_prepareIngredient_r1_positionningCup_default() {
		entryAction_main_region_prepareIngredient_r1_positionningCup();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_prepareIngredient_r1_positionningCup;
	}
	
	/* 'default' enter sequence for state getTeaBag */
	private void enterSequence_main_region_prepareIngredient_r1_getTeaBag_default() {
		entryAction_main_region_prepareIngredient_r1_getTeaBag();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_prepareIngredient_r1_getTeaBag;
	}
	
	/* 'default' enter sequence for state cupPositionned */
	private void enterSequence_main_region_prepareIngredient_r1_cupPositionned_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_prepareIngredient_r1_cupPositionned;
	}
	
	/* 'default' enter sequence for state Heating */
	private void enterSequence_main_region_prepareIngredient_r2_Heating_default() {
		nextStateIndex = 1;
		stateVector[1] = State.main_region_prepareIngredient_r2_Heating;
	}
	
	/* 'default' enter sequence for state IsHot */
	private void enterSequence_main_region_prepareIngredient_r2_IsHot_default() {
		entryAction_main_region_prepareIngredient_r2_IsHot();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_prepareIngredient_r2_IsHot;
	}
	
	/* 'default' enter sequence for state poorIngredient */
	private void enterSequence_main_region_poorIngredient_default() {
		enterSequence_main_region_poorIngredient_r1_default();
		enterSequence_main_region_poorIngredient_r2_default();
	}
	
	/* 'default' enter sequence for state poorSugar */
	private void enterSequence_main_region_poorIngredient_r1_poorSugar_default() {
		entryAction_main_region_poorIngredient_r1_poorSugar();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_poorIngredient_r1_poorSugar;
	}
	
	/* 'default' enter sequence for state sugarPoored */
	private void enterSequence_main_region_poorIngredient_r1_sugarPoored_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_poorIngredient_r1_sugarPoored;
	}
	
	/* 'default' enter sequence for state poorDrink */
	private void enterSequence_main_region_poorIngredient_r2_poorDrink_default() {
		entryAction_main_region_poorIngredient_r2_poorDrink();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_poorIngredient_r2_poorDrink;
	}
	
	/* 'default' enter sequence for state drinkPoored */
	private void enterSequence_main_region_poorIngredient_r2_drinkPoored_default() {
		entryAction_main_region_poorIngredient_r2_drinkPoored();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_poorIngredient_r2_drinkPoored;
	}
	
	/* 'default' enter sequence for state DrinkDistribute */
	private void enterSequence_main_region_DrinkDistribute_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_DrinkDistribute;
	}
	
	/* Default enter sequence for state null */
	private void enterSequence_main_region__final__default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region__final_;
	}
	
	/* 'default' enter sequence for state brew */
	private void enterSequence_main_region_brew_default() {
		entryAction_main_region_brew();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_brew;
	}
	
	/* 'default' enter sequence for state dropTeaBag */
	private void enterSequence_main_region_dropTeaBag_default() {
		entryAction_main_region_dropTeaBag();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_dropTeaBag;
	}
	
	/* 'default' enter sequence for region main region */
	private void enterSequence_main_region_default() {
		react_main_region__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_prepareIngredient_r1_default() {
		react_main_region_prepareIngredient_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_main_region_prepareIngredient_r2_default() {
		react_main_region_prepareIngredient_r2__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_poorIngredient_r1_default() {
		react_main_region_poorIngredient_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_main_region_poorIngredient_r2_default() {
		react_main_region_poorIngredient_r2__entry_Default();
	}
	
	/* Default exit sequence for state prepareIngredient */
	private void exitSequence_main_region_prepareIngredient() {
		exitSequence_main_region_prepareIngredient_r1();
		exitSequence_main_region_prepareIngredient_r2();
	}
	
	/* Default exit sequence for state positionningCup */
	private void exitSequence_main_region_prepareIngredient_r1_positionningCup() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_prepareIngredient_r1_positionningCup();
	}
	
	/* Default exit sequence for state getTeaBag */
	private void exitSequence_main_region_prepareIngredient_r1_getTeaBag() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_prepareIngredient_r1_getTeaBag();
	}
	
	/* Default exit sequence for state cupPositionned */
	private void exitSequence_main_region_prepareIngredient_r1_cupPositionned() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Heating */
	private void exitSequence_main_region_prepareIngredient_r2_Heating() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state IsHot */
	private void exitSequence_main_region_prepareIngredient_r2_IsHot() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
		
		exitAction_main_region_prepareIngredient_r2_IsHot();
	}
	
	/* Default exit sequence for state poorIngredient */
	private void exitSequence_main_region_poorIngredient() {
		exitSequence_main_region_poorIngredient_r1();
		exitSequence_main_region_poorIngredient_r2();
	}
	
	/* Default exit sequence for state poorSugar */
	private void exitSequence_main_region_poorIngredient_r1_poorSugar() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state sugarPoored */
	private void exitSequence_main_region_poorIngredient_r1_sugarPoored() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state poorDrink */
	private void exitSequence_main_region_poorIngredient_r2_poorDrink() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state drinkPoored */
	private void exitSequence_main_region_poorIngredient_r2_drinkPoored() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
		
		exitAction_main_region_poorIngredient_r2_drinkPoored();
	}
	
	/* Default exit sequence for state DrinkDistribute */
	private void exitSequence_main_region_DrinkDistribute() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for final state. */
	private void exitSequence_main_region__final_() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state brew */
	private void exitSequence_main_region_brew() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_brew();
	}
	
	/* Default exit sequence for state dropTeaBag */
	private void exitSequence_main_region_dropTeaBag() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_dropTeaBag();
	}
	
	/* Default exit sequence for region main region */
	private void exitSequence_main_region() {
		switch (stateVector[0]) {
		case main_region_prepareIngredient_r1_positionningCup:
			exitSequence_main_region_prepareIngredient_r1_positionningCup();
			break;
		case main_region_prepareIngredient_r1_getTeaBag:
			exitSequence_main_region_prepareIngredient_r1_getTeaBag();
			break;
		case main_region_prepareIngredient_r1_cupPositionned:
			exitSequence_main_region_prepareIngredient_r1_cupPositionned();
			break;
		case main_region_poorIngredient_r1_poorSugar:
			exitSequence_main_region_poorIngredient_r1_poorSugar();
			break;
		case main_region_poorIngredient_r1_sugarPoored:
			exitSequence_main_region_poorIngredient_r1_sugarPoored();
			break;
		case main_region_DrinkDistribute:
			exitSequence_main_region_DrinkDistribute();
			break;
		case main_region__final_:
			exitSequence_main_region__final_();
			break;
		case main_region_brew:
			exitSequence_main_region_brew();
			break;
		case main_region_dropTeaBag:
			exitSequence_main_region_dropTeaBag();
			break;
		default:
			break;
		}
		
		switch (stateVector[1]) {
		case main_region_prepareIngredient_r2_Heating:
			exitSequence_main_region_prepareIngredient_r2_Heating();
			break;
		case main_region_prepareIngredient_r2_IsHot:
			exitSequence_main_region_prepareIngredient_r2_IsHot();
			break;
		case main_region_poorIngredient_r2_poorDrink:
			exitSequence_main_region_poorIngredient_r2_poorDrink();
			break;
		case main_region_poorIngredient_r2_drinkPoored:
			exitSequence_main_region_poorIngredient_r2_drinkPoored();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_main_region_prepareIngredient_r1() {
		switch (stateVector[0]) {
		case main_region_prepareIngredient_r1_positionningCup:
			exitSequence_main_region_prepareIngredient_r1_positionningCup();
			break;
		case main_region_prepareIngredient_r1_getTeaBag:
			exitSequence_main_region_prepareIngredient_r1_getTeaBag();
			break;
		case main_region_prepareIngredient_r1_cupPositionned:
			exitSequence_main_region_prepareIngredient_r1_cupPositionned();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r2 */
	private void exitSequence_main_region_prepareIngredient_r2() {
		switch (stateVector[1]) {
		case main_region_prepareIngredient_r2_Heating:
			exitSequence_main_region_prepareIngredient_r2_Heating();
			break;
		case main_region_prepareIngredient_r2_IsHot:
			exitSequence_main_region_prepareIngredient_r2_IsHot();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_main_region_poorIngredient_r1() {
		switch (stateVector[0]) {
		case main_region_poorIngredient_r1_poorSugar:
			exitSequence_main_region_poorIngredient_r1_poorSugar();
			break;
		case main_region_poorIngredient_r1_sugarPoored:
			exitSequence_main_region_poorIngredient_r1_sugarPoored();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r2 */
	private void exitSequence_main_region_poorIngredient_r2() {
		switch (stateVector[1]) {
		case main_region_poorIngredient_r2_poorDrink:
			exitSequence_main_region_poorIngredient_r2_poorDrink();
			break;
		case main_region_poorIngredient_r2_drinkPoored:
			exitSequence_main_region_poorIngredient_r2_drinkPoored();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_prepareIngredient_r1__entry_Default() {
		enterSequence_main_region_prepareIngredient_r1_getTeaBag_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_prepareIngredient_r2__entry_Default() {
		enterSequence_main_region_prepareIngredient_r2_Heating_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_poorIngredient_r1__entry_Default() {
		enterSequence_main_region_poorIngredient_r1_poorSugar_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_poorIngredient_r2__entry_Default() {
		enterSequence_main_region_poorIngredient_r2_poorDrink_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region__entry_Default() {
		enterSequence_main_region_prepareIngredient_default();
	}
	
	/* The reactions of state null. */
	private void react_main_region__sync0() {
		enterSequence_main_region_poorIngredient_default();
	}
	
	/* The reactions of state null. */
	private void react_main_region__sync1() {
		enterSequence_main_region_brew_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean main_region_prepareIngredient_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_prepareIngredient_r1_positionningCup_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[0]) {
				exitSequence_main_region_prepareIngredient_r1_positionningCup();
				enterSequence_main_region_prepareIngredient_r1_cupPositionned_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_prepareIngredient_r1_getTeaBag_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[1]) {
				exitSequence_main_region_prepareIngredient_r1_getTeaBag();
				enterSequence_main_region_prepareIngredient_r1_positionningCup_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_prepareIngredient_r1_cupPositionned_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((true && isStateActive(State.main_region_prepareIngredient_r2_IsHot)) && timeEvents[2])) {
				exitSequence_main_region_prepareIngredient();
				react_main_region__sync0();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_prepareIngredient_r2_Heating_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.isHot) {
				exitSequence_main_region_prepareIngredient_r2_Heating();
				enterSequence_main_region_prepareIngredient_r2_IsHot_default();
				main_region_prepareIngredient_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_prepareIngredient_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_prepareIngredient_r2_IsHot_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((timeEvents[2] && isStateActive(State.main_region_prepareIngredient_r1_cupPositionned)) && true)) {
				exitSequence_main_region_prepareIngredient();
				react_main_region__sync0();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_prepareIngredient_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_poorIngredient_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_poorIngredient_r1_poorSugar_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.sugarFinishPoored) {
				exitSequence_main_region_poorIngredient_r1_poorSugar();
				enterSequence_main_region_poorIngredient_r1_sugarPoored_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_poorIngredient_r1_sugarPoored_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((true && isStateActive(State.main_region_poorIngredient_r2_drinkPoored)) && timeEvents[3])) {
				exitSequence_main_region_poorIngredient();
				react_main_region__sync1();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_poorIngredient_r2_poorDrink_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.drinkFinishPoored) {
				exitSequence_main_region_poorIngredient_r2_poorDrink();
				enterSequence_main_region_poorIngredient_r2_drinkPoored_default();
				main_region_poorIngredient_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_poorIngredient_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_poorIngredient_r2_drinkPoored_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((timeEvents[3] && isStateActive(State.main_region_poorIngredient_r1_sugarPoored)) && true)) {
				exitSequence_main_region_poorIngredient();
				react_main_region__sync1();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_poorIngredient_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_DrinkDistribute_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.drinkPickedUp) {
				exitSequence_main_region_DrinkDistribute();
				enterSequence_main_region__final__default();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region__final__react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_brew_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[4]) {
				exitSequence_main_region_brew();
				enterSequence_main_region_dropTeaBag_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_dropTeaBag_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[5]) {
				exitSequence_main_region_dropTeaBag();
				enterSequence_main_region_DrinkDistribute_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
}
