/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.expresso;

import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public class ExpressoStatemachine implements IExpressoStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private List<SCInterfaceListener> listeners = new LinkedList<SCInterfaceListener>();
		
		public List<SCInterfaceListener> getListeners() {
			return listeners;
		}
		private boolean coffeeIsGrinded;
		
		
		public void raiseCoffeeIsGrinded() {
			synchronized(ExpressoStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							coffeeIsGrinded = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean isHot;
		
		
		public void raiseIsHot() {
			synchronized(ExpressoStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							isHot = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean cupIsPlaced;
		
		
		public void raiseCupIsPlaced() {
			synchronized(ExpressoStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							cupIsPlaced = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean sugarFinishPoored;
		
		
		public void raiseSugarFinishPoored() {
			synchronized(ExpressoStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							sugarFinishPoored = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean drinkFinishPoored;
		
		
		public void raiseDrinkFinishPoored() {
			synchronized(ExpressoStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							drinkFinishPoored = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean drinkPickedUp;
		
		
		public void raiseDrinkPickedUp() {
			synchronized(ExpressoStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							drinkPickedUp = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean coffeeIsGround;
		
		
		public void raiseCoffeeIsGround() {
			synchronized(ExpressoStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							coffeeIsGround = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean grindingCoffee;
		
		
		public boolean isRaisedGrindingCoffee() {
			synchronized(ExpressoStatemachine.this) {
				return grindingCoffee;
			}
		}
		
		protected void raiseGrindingCoffee() {
			synchronized(ExpressoStatemachine.this) {
				grindingCoffee = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onGrindingCoffeeRaised();
				}
			}
		}
		
		private boolean groundingCoffee;
		
		
		public boolean isRaisedGroundingCoffee() {
			synchronized(ExpressoStatemachine.this) {
				return groundingCoffee;
			}
		}
		
		protected void raiseGroundingCoffee() {
			synchronized(ExpressoStatemachine.this) {
				groundingCoffee = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onGroundingCoffeeRaised();
				}
			}
		}
		
		private boolean placeCup;
		
		
		public boolean isRaisedPlaceCup() {
			synchronized(ExpressoStatemachine.this) {
				return placeCup;
			}
		}
		
		protected void raisePlaceCup() {
			synchronized(ExpressoStatemachine.this) {
				placeCup = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPlaceCupRaised();
				}
			}
		}
		
		private boolean heating;
		
		
		public boolean isRaisedHeating() {
			synchronized(ExpressoStatemachine.this) {
				return heating;
			}
		}
		
		protected void raiseHeating() {
			synchronized(ExpressoStatemachine.this) {
				heating = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onHeatingRaised();
				}
			}
		}
		
		private boolean pooringSugar;
		
		
		public boolean isRaisedPooringSugar() {
			synchronized(ExpressoStatemachine.this) {
				return pooringSugar;
			}
		}
		
		protected void raisePooringSugar() {
			synchronized(ExpressoStatemachine.this) {
				pooringSugar = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPooringSugarRaised();
				}
			}
		}
		
		private boolean pooringDrink;
		
		
		public boolean isRaisedPooringDrink() {
			synchronized(ExpressoStatemachine.this) {
				return pooringDrink;
			}
		}
		
		protected void raisePooringDrink() {
			synchronized(ExpressoStatemachine.this) {
				pooringDrink = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPooringDrinkRaised();
				}
			}
		}
		
		protected void clearEvents() {
			coffeeIsGrinded = false;
			isHot = false;
			cupIsPlaced = false;
			sugarFinishPoored = false;
			drinkFinishPoored = false;
			drinkPickedUp = false;
			coffeeIsGround = false;
		}
		protected void clearOutEvents() {
		
		grindingCoffee = false;
		groundingCoffee = false;
		placeCup = false;
		heating = false;
		pooringSugar = false;
		pooringDrink = false;
		}
		
	}
	
	
	protected SCInterfaceImpl sCInterface;
	
	private boolean initialized = false;
	
	public enum State {
		main_region_PlacingPod,
		main_region_PlacingPod_r1_grindcoffee,
		main_region_PlacingPod_r1_Ingredient,
		main_region_PlacingPod_r1_Ingredient_r1_positionningCup,
		main_region_PlacingPod_r1_Ingredient_r1__final_,
		main_region_PlacingPod_r1_Ingredient_r2_groundCoffee,
		main_region_PlacingPod_r1_Ingredient_r2__final_,
		main_region_PlacingPod_r1__final_,
		main_region_PlacingPod_r2_beginHeating,
		main_region_PlacingPod_r2__final_,
		main_region_poorIngredient,
		main_region_poorIngredient_r1_poorSugar,
		main_region_poorIngredient_r1__final_,
		main_region_poorIngredient_r2_poorDrink,
		main_region_poorIngredient_r2__final_,
		main_region_expressoDistributed,
		main_region__final_,
		$NullState$
	};
	
	private final State[] stateVector = new State[3];
	
	private int nextStateIndex;
	
	private BlockingQueue<Runnable> inEventQueue = new LinkedBlockingQueue<Runnable>();
	private boolean isRunningCycle = false;
	public ExpressoStatemachine() {
		sCInterface = new SCInterfaceImpl();
	}
	
	public synchronized void init() {
		this.initialized = true;
		for (int i = 0; i < 3; i++) {
			stateVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
	}
	
	public synchronized void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		enterSequence_main_region_default();
	}
	
	public synchronized void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		
		if (isRunningCycle) {
			return;
		}
		isRunningCycle = true;
		
		clearOutEvents();
	
		Runnable task = getNextEvent();
		if (task == null) {
			task = getDefaultEvent();
		}
		
		while (task != null) {
			task.run();
			clearEvents();
			task = getNextEvent();
		}
		
		isRunningCycle = false;
	}
	
	protected synchronized void singleCycle() {
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case main_region_PlacingPod_r1_grindcoffee:
				main_region_PlacingPod_r1_grindcoffee_react(true);
				break;
			case main_region_PlacingPod_r1_Ingredient_r1_positionningCup:
				main_region_PlacingPod_r1_Ingredient_r1_positionningCup_react(true);
				break;
			case main_region_PlacingPod_r1_Ingredient_r1__final_:
				main_region_PlacingPod_r1_Ingredient_r1__final__react(true);
				break;
			case main_region_PlacingPod_r1_Ingredient_r2_groundCoffee:
				main_region_PlacingPod_r1_Ingredient_r2_groundCoffee_react(true);
				break;
			case main_region_PlacingPod_r1_Ingredient_r2__final_:
				main_region_PlacingPod_r1_Ingredient_r2__final__react(true);
				break;
			case main_region_PlacingPod_r1__final_:
				main_region_PlacingPod_r1__final__react(true);
				break;
			case main_region_PlacingPod_r2_beginHeating:
				main_region_PlacingPod_r2_beginHeating_react(true);
				break;
			case main_region_PlacingPod_r2__final_:
				main_region_PlacingPod_r2__final__react(true);
				break;
			case main_region_poorIngredient_r1_poorSugar:
				main_region_poorIngredient_r1_poorSugar_react(true);
				break;
			case main_region_poorIngredient_r1__final_:
				main_region_poorIngredient_r1__final__react(true);
				break;
			case main_region_poorIngredient_r2_poorDrink:
				main_region_poorIngredient_r2_poorDrink_react(true);
				break;
			case main_region_poorIngredient_r2__final_:
				main_region_poorIngredient_r2__final__react(true);
				break;
			case main_region_expressoDistributed:
				main_region_expressoDistributed_react(true);
				break;
			case main_region__final_:
				main_region__final__react(true);
				break;
			default:
				// $NullState$
			}
		}
	}
	
	protected Runnable getNextEvent() {
		if(!inEventQueue.isEmpty()) {
			return inEventQueue.poll();
		}
		return null;
	}
	
	protected Runnable getDefaultEvent() {
		return new Runnable() {
			@Override
			public void run() {
				singleCycle();
			}
		};
	}
	
	public synchronized void exit() {
		exitSequence_main_region();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NullState$||stateVector[1] != State.$NullState$||stateVector[2] != State.$NullState$;
	}
	
	/** 
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return (stateVector[0] == State.main_region_PlacingPod_r1_Ingredient_r1__final_ || stateVector[0] == State.main_region_PlacingPod_r1__final_ || stateVector[0] == State.main_region_poorIngredient_r1__final_ || stateVector[0] == State.main_region__final_) && (stateVector[1] == State.main_region_PlacingPod_r1_Ingredient_r2__final_ || stateVector[1] == State.$NullState$ || stateVector[1] == State.main_region_poorIngredient_r2__final_ || stateVector[1] == State.$NullState$) && (stateVector[2] == State.main_region_PlacingPod_r2__final_ || stateVector[2] == State.$NullState$);
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCInterface.clearEvents();
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
		sCInterface.clearOutEvents();
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case main_region_PlacingPod:
			return stateVector[0].ordinal() >= State.
					main_region_PlacingPod.ordinal()&& stateVector[0].ordinal() <= State.main_region_PlacingPod_r2__final_.ordinal();
		case main_region_PlacingPod_r1_grindcoffee:
			return stateVector[0] == State.main_region_PlacingPod_r1_grindcoffee;
		case main_region_PlacingPod_r1_Ingredient:
			return stateVector[0].ordinal() >= State.
					main_region_PlacingPod_r1_Ingredient.ordinal()&& stateVector[0].ordinal() <= State.main_region_PlacingPod_r1_Ingredient_r2__final_.ordinal();
		case main_region_PlacingPod_r1_Ingredient_r1_positionningCup:
			return stateVector[0] == State.main_region_PlacingPod_r1_Ingredient_r1_positionningCup;
		case main_region_PlacingPod_r1_Ingredient_r1__final_:
			return stateVector[0] == State.main_region_PlacingPod_r1_Ingredient_r1__final_;
		case main_region_PlacingPod_r1_Ingredient_r2_groundCoffee:
			return stateVector[1] == State.main_region_PlacingPod_r1_Ingredient_r2_groundCoffee;
		case main_region_PlacingPod_r1_Ingredient_r2__final_:
			return stateVector[1] == State.main_region_PlacingPod_r1_Ingredient_r2__final_;
		case main_region_PlacingPod_r1__final_:
			return stateVector[0] == State.main_region_PlacingPod_r1__final_;
		case main_region_PlacingPod_r2_beginHeating:
			return stateVector[2] == State.main_region_PlacingPod_r2_beginHeating;
		case main_region_PlacingPod_r2__final_:
			return stateVector[2] == State.main_region_PlacingPod_r2__final_;
		case main_region_poorIngredient:
			return stateVector[0].ordinal() >= State.
					main_region_poorIngredient.ordinal()&& stateVector[0].ordinal() <= State.main_region_poorIngredient_r2__final_.ordinal();
		case main_region_poorIngredient_r1_poorSugar:
			return stateVector[0] == State.main_region_poorIngredient_r1_poorSugar;
		case main_region_poorIngredient_r1__final_:
			return stateVector[0] == State.main_region_poorIngredient_r1__final_;
		case main_region_poorIngredient_r2_poorDrink:
			return stateVector[1] == State.main_region_poorIngredient_r2_poorDrink;
		case main_region_poorIngredient_r2__final_:
			return stateVector[1] == State.main_region_poorIngredient_r2__final_;
		case main_region_expressoDistributed:
			return stateVector[0] == State.main_region_expressoDistributed;
		case main_region__final_:
			return stateVector[0] == State.main_region__final_;
		default:
			return false;
		}
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	public synchronized void raiseCoffeeIsGrinded() {
		sCInterface.raiseCoffeeIsGrinded();
	}
	
	public synchronized void raiseIsHot() {
		sCInterface.raiseIsHot();
	}
	
	public synchronized void raiseCupIsPlaced() {
		sCInterface.raiseCupIsPlaced();
	}
	
	public synchronized void raiseSugarFinishPoored() {
		sCInterface.raiseSugarFinishPoored();
	}
	
	public synchronized void raiseDrinkFinishPoored() {
		sCInterface.raiseDrinkFinishPoored();
	}
	
	public synchronized void raiseDrinkPickedUp() {
		sCInterface.raiseDrinkPickedUp();
	}
	
	public synchronized void raiseCoffeeIsGround() {
		sCInterface.raiseCoffeeIsGround();
	}
	
	public synchronized boolean isRaisedGrindingCoffee() {
		return sCInterface.isRaisedGrindingCoffee();
	}
	
	public synchronized boolean isRaisedGroundingCoffee() {
		return sCInterface.isRaisedGroundingCoffee();
	}
	
	public synchronized boolean isRaisedPlaceCup() {
		return sCInterface.isRaisedPlaceCup();
	}
	
	public synchronized boolean isRaisedHeating() {
		return sCInterface.isRaisedHeating();
	}
	
	public synchronized boolean isRaisedPooringSugar() {
		return sCInterface.isRaisedPooringSugar();
	}
	
	public synchronized boolean isRaisedPooringDrink() {
		return sCInterface.isRaisedPooringDrink();
	}
	
	/* 'default' enter sequence for state PlacingPod */
	private void enterSequence_main_region_PlacingPod_default() {
		enterSequence_main_region_PlacingPod_r1_default();
		enterSequence_main_region_PlacingPod_r2_default();
	}
	
	/* 'default' enter sequence for state grindcoffee */
	private void enterSequence_main_region_PlacingPod_r1_grindcoffee_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_PlacingPod_r1_grindcoffee;
	}
	
	/* 'default' enter sequence for state Ingredient */
	private void enterSequence_main_region_PlacingPod_r1_Ingredient_default() {
		enterSequence_main_region_PlacingPod_r1_Ingredient_r1_default();
		enterSequence_main_region_PlacingPod_r1_Ingredient_r2_default();
	}
	
	/* 'default' enter sequence for state positionningCup */
	private void enterSequence_main_region_PlacingPod_r1_Ingredient_r1_positionningCup_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_PlacingPod_r1_Ingredient_r1_positionningCup;
	}
	
	/* Default enter sequence for state null */
	private void enterSequence_main_region_PlacingPod_r1_Ingredient_r1__final__default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_PlacingPod_r1_Ingredient_r1__final_;
	}
	
	/* 'default' enter sequence for state groundCoffee */
	private void enterSequence_main_region_PlacingPod_r1_Ingredient_r2_groundCoffee_default() {
		nextStateIndex = 1;
		stateVector[1] = State.main_region_PlacingPod_r1_Ingredient_r2_groundCoffee;
	}
	
	/* Default enter sequence for state null */
	private void enterSequence_main_region_PlacingPod_r1_Ingredient_r2__final__default() {
		nextStateIndex = 1;
		stateVector[1] = State.main_region_PlacingPod_r1_Ingredient_r2__final_;
	}
	
	/* 'default' enter sequence for state beginHeating */
	private void enterSequence_main_region_PlacingPod_r2_beginHeating_default() {
		nextStateIndex = 2;
		stateVector[2] = State.main_region_PlacingPod_r2_beginHeating;
	}
	
	/* Default enter sequence for state null */
	private void enterSequence_main_region_PlacingPod_r2__final__default() {
		nextStateIndex = 2;
		stateVector[2] = State.main_region_PlacingPod_r2__final_;
	}
	
	/* Default enter sequence for state null */
	private void enterSequence_main_region_poorIngredient_r1__final__default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_poorIngredient_r1__final_;
	}
	
	/* Default enter sequence for state null */
	private void enterSequence_main_region_poorIngredient_r2__final__default() {
		nextStateIndex = 1;
		stateVector[1] = State.main_region_poorIngredient_r2__final_;
	}
	
	/* 'default' enter sequence for state expressoDistributed */
	private void enterSequence_main_region_expressoDistributed_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_expressoDistributed;
	}
	
	/* Default enter sequence for state null */
	private void enterSequence_main_region__final__default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region__final_;
	}
	
	/* 'default' enter sequence for region main region */
	private void enterSequence_main_region_default() {
		react_main_region__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_PlacingPod_r1_default() {
		react_main_region_PlacingPod_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_PlacingPod_r1_Ingredient_r1_default() {
		react_main_region_PlacingPod_r1_Ingredient_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_main_region_PlacingPod_r1_Ingredient_r2_default() {
		react_main_region_PlacingPod_r1_Ingredient_r2__entry_Default();
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_main_region_PlacingPod_r2_default() {
		react_main_region_PlacingPod_r2__entry_Default();
	}
	
	/* Default exit sequence for state grindcoffee */
	private void exitSequence_main_region_PlacingPod_r1_grindcoffee() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state positionningCup */
	private void exitSequence_main_region_PlacingPod_r1_Ingredient_r1_positionningCup() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for final state. */
	private void exitSequence_main_region_PlacingPod_r1_Ingredient_r1__final_() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state groundCoffee */
	private void exitSequence_main_region_PlacingPod_r1_Ingredient_r2_groundCoffee() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for final state. */
	private void exitSequence_main_region_PlacingPod_r1_Ingredient_r2__final_() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for final state. */
	private void exitSequence_main_region_PlacingPod_r1__final_() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state beginHeating */
	private void exitSequence_main_region_PlacingPod_r2_beginHeating() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
	}
	
	/* Default exit sequence for final state. */
	private void exitSequence_main_region_PlacingPod_r2__final_() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
	}
	
	/* Default exit sequence for state poorIngredient */
	private void exitSequence_main_region_poorIngredient() {
		exitSequence_main_region_poorIngredient_r1();
		exitSequence_main_region_poorIngredient_r2();
	}
	
	/* Default exit sequence for state poorSugar */
	private void exitSequence_main_region_poorIngredient_r1_poorSugar() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for final state. */
	private void exitSequence_main_region_poorIngredient_r1__final_() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state poorDrink */
	private void exitSequence_main_region_poorIngredient_r2_poorDrink() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for final state. */
	private void exitSequence_main_region_poorIngredient_r2__final_() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state expressoDistributed */
	private void exitSequence_main_region_expressoDistributed() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for final state. */
	private void exitSequence_main_region__final_() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for region main region */
	private void exitSequence_main_region() {
		switch (stateVector[0]) {
		case main_region_PlacingPod_r1_grindcoffee:
			exitSequence_main_region_PlacingPod_r1_grindcoffee();
			break;
		case main_region_PlacingPod_r1_Ingredient_r1_positionningCup:
			exitSequence_main_region_PlacingPod_r1_Ingredient_r1_positionningCup();
			break;
		case main_region_PlacingPod_r1_Ingredient_r1__final_:
			exitSequence_main_region_PlacingPod_r1_Ingredient_r1__final_();
			break;
		case main_region_PlacingPod_r1__final_:
			exitSequence_main_region_PlacingPod_r1__final_();
			break;
		case main_region_poorIngredient_r1_poorSugar:
			exitSequence_main_region_poorIngredient_r1_poorSugar();
			break;
		case main_region_poorIngredient_r1__final_:
			exitSequence_main_region_poorIngredient_r1__final_();
			break;
		case main_region_expressoDistributed:
			exitSequence_main_region_expressoDistributed();
			break;
		case main_region__final_:
			exitSequence_main_region__final_();
			break;
		default:
			break;
		}
		
		switch (stateVector[1]) {
		case main_region_PlacingPod_r1_Ingredient_r2_groundCoffee:
			exitSequence_main_region_PlacingPod_r1_Ingredient_r2_groundCoffee();
			break;
		case main_region_PlacingPod_r1_Ingredient_r2__final_:
			exitSequence_main_region_PlacingPod_r1_Ingredient_r2__final_();
			break;
		case main_region_poorIngredient_r2_poorDrink:
			exitSequence_main_region_poorIngredient_r2_poorDrink();
			break;
		case main_region_poorIngredient_r2__final_:
			exitSequence_main_region_poorIngredient_r2__final_();
			break;
		default:
			break;
		}
		
		switch (stateVector[2]) {
		case main_region_PlacingPod_r2_beginHeating:
			exitSequence_main_region_PlacingPod_r2_beginHeating();
			break;
		case main_region_PlacingPod_r2__final_:
			exitSequence_main_region_PlacingPod_r2__final_();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_main_region_poorIngredient_r1() {
		switch (stateVector[0]) {
		case main_region_poorIngredient_r1_poorSugar:
			exitSequence_main_region_poorIngredient_r1_poorSugar();
			break;
		case main_region_poorIngredient_r1__final_:
			exitSequence_main_region_poorIngredient_r1__final_();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r2 */
	private void exitSequence_main_region_poorIngredient_r2() {
		switch (stateVector[1]) {
		case main_region_poorIngredient_r2_poorDrink:
			exitSequence_main_region_poorIngredient_r2_poorDrink();
			break;
		case main_region_poorIngredient_r2__final_:
			exitSequence_main_region_poorIngredient_r2__final_();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region__entry_Default() {
		enterSequence_main_region_PlacingPod_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_PlacingPod_r1__entry_Default() {
		enterSequence_main_region_PlacingPod_r1_grindcoffee_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_PlacingPod_r1_Ingredient_r1__entry_Default() {
		enterSequence_main_region_PlacingPod_r1_Ingredient_r1_positionningCup_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_PlacingPod_r1_Ingredient_r2__entry_Default() {
		enterSequence_main_region_PlacingPod_r1_Ingredient_r2_groundCoffee_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_PlacingPod_r2__entry_Default() {
		enterSequence_main_region_PlacingPod_r2_beginHeating_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean main_region_PlacingPod_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_PlacingPod_r1_grindcoffee_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.coffeeIsGrinded) {
				exitSequence_main_region_PlacingPod_r1_grindcoffee();
				enterSequence_main_region_PlacingPod_r1_Ingredient_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_PlacingPod_r1_Ingredient_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		return did_transition;
	}
	
	private boolean main_region_PlacingPod_r1_Ingredient_r1_positionningCup_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.cupIsPlaced) {
				exitSequence_main_region_PlacingPod_r1_Ingredient_r1_positionningCup();
				enterSequence_main_region_PlacingPod_r1_Ingredient_r1__final__default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_PlacingPod_r1_Ingredient_r1__final__react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		return did_transition;
	}
	
	private boolean main_region_PlacingPod_r1_Ingredient_r2_groundCoffee_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.coffeeIsGround) {
				exitSequence_main_region_PlacingPod_r1_Ingredient_r2_groundCoffee();
				enterSequence_main_region_PlacingPod_r1_Ingredient_r2__final__default();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_PlacingPod_r1_Ingredient_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_PlacingPod_r1_Ingredient_r2__final__react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = main_region_PlacingPod_r1_Ingredient_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_PlacingPod_r1__final__react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		return did_transition;
	}
	
	private boolean main_region_PlacingPod_r2_beginHeating_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.isHot) {
				exitSequence_main_region_PlacingPod_r2_beginHeating();
				enterSequence_main_region_PlacingPod_r2__final__default();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_PlacingPod_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_PlacingPod_r2__final__react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = main_region_PlacingPod_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_poorIngredient_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			exitSequence_main_region_poorIngredient();
			enterSequence_main_region_expressoDistributed_default();
			react();
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_poorIngredient_r1_poorSugar_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.sugarFinishPoored) {
				exitSequence_main_region_poorIngredient_r1_poorSugar();
				enterSequence_main_region_poorIngredient_r1__final__default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_poorIngredient_r1__final__react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		return did_transition;
	}
	
	private boolean main_region_poorIngredient_r2_poorDrink_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.drinkFinishPoored) {
				exitSequence_main_region_poorIngredient_r2_poorDrink();
				enterSequence_main_region_poorIngredient_r2__final__default();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_poorIngredient_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_poorIngredient_r2__final__react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = main_region_poorIngredient_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_expressoDistributed_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.drinkPickedUp) {
				exitSequence_main_region_expressoDistributed();
				enterSequence_main_region__final__default();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region__final__react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
}
