/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.expresso;

import fr.univcotedazur.polytech.si4.fsm.project.ITimer;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public class ExpressoStatemachine implements IExpressoStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private List<SCInterfaceListener> listeners = new LinkedList<SCInterfaceListener>();
		
		public List<SCInterfaceListener> getListeners() {
			return listeners;
		}
		private boolean isHot;
		
		
		public void raiseIsHot() {
			synchronized(ExpressoStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							isHot = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean sugarFinishPoored;
		
		
		public void raiseSugarFinishPoored() {
			synchronized(ExpressoStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							sugarFinishPoored = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean drinkFinishPoored;
		
		
		public void raiseDrinkFinishPoored() {
			synchronized(ExpressoStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							drinkFinishPoored = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean drinkPickedUp;
		
		
		public void raiseDrinkPickedUp() {
			synchronized(ExpressoStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							drinkPickedUp = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean prepare;
		
		
		public void raisePrepare() {
			synchronized(ExpressoStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							prepare = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean grindingCoffee;
		
		
		public boolean isRaisedGrindingCoffee() {
			synchronized(ExpressoStatemachine.this) {
				return grindingCoffee;
			}
		}
		
		protected void raiseGrindingCoffee() {
			synchronized(ExpressoStatemachine.this) {
				grindingCoffee = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onGrindingCoffeeRaised();
				}
			}
		}
		
		private boolean groundingCoffee;
		
		
		public boolean isRaisedGroundingCoffee() {
			synchronized(ExpressoStatemachine.this) {
				return groundingCoffee;
			}
		}
		
		protected void raiseGroundingCoffee() {
			synchronized(ExpressoStatemachine.this) {
				groundingCoffee = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onGroundingCoffeeRaised();
				}
			}
		}
		
		private boolean placeCup;
		
		
		public boolean isRaisedPlaceCup() {
			synchronized(ExpressoStatemachine.this) {
				return placeCup;
			}
		}
		
		protected void raisePlaceCup() {
			synchronized(ExpressoStatemachine.this) {
				placeCup = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPlaceCupRaised();
				}
			}
		}
		
		private boolean heating;
		
		
		public boolean isRaisedHeating() {
			synchronized(ExpressoStatemachine.this) {
				return heating;
			}
		}
		
		protected void raiseHeating() {
			synchronized(ExpressoStatemachine.this) {
				heating = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onHeatingRaised();
				}
			}
		}
		
		private boolean pooringSugar;
		
		
		public boolean isRaisedPooringSugar() {
			synchronized(ExpressoStatemachine.this) {
				return pooringSugar;
			}
		}
		
		protected void raisePooringSugar() {
			synchronized(ExpressoStatemachine.this) {
				pooringSugar = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPooringSugarRaised();
				}
			}
		}
		
		private boolean pooringDrink;
		
		
		public boolean isRaisedPooringDrink() {
			synchronized(ExpressoStatemachine.this) {
				return pooringDrink;
			}
		}
		
		protected void raisePooringDrink() {
			synchronized(ExpressoStatemachine.this) {
				pooringDrink = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPooringDrinkRaised();
				}
			}
		}
		
		protected void clearEvents() {
			isHot = false;
			sugarFinishPoored = false;
			drinkFinishPoored = false;
			drinkPickedUp = false;
			prepare = false;
		}
		protected void clearOutEvents() {
		
		grindingCoffee = false;
		groundingCoffee = false;
		placeCup = false;
		heating = false;
		pooringSugar = false;
		pooringDrink = false;
		}
		
	}
	
	
	protected SCInterfaceImpl sCInterface;
	
	private boolean initialized = false;
	
	public enum State {
		main_region_PlacingPod,
		main_region_PlacingPod_r1_grindcoffee,
		main_region_PlacingPod_r1_Ingredient,
		main_region_PlacingPod_r1_Ingredient_r1_positionningCup,
		main_region_PlacingPod_r1_Ingredient_r1_cupPlaced,
		main_region_PlacingPod_r1_Ingredient_r2_groundCoffee,
		main_region_PlacingPod_r1_Ingredient_r2_coffeeGround,
		main_region_PlacingPod_r2_beginHeating,
		main_region_PlacingPod_r2_IsHot,
		main_region_poorIngredient,
		main_region_poorIngredient_r1_poorSugar,
		main_region_poorIngredient_r1_sugarPoored,
		main_region_poorIngredient_r2_poorDrink,
		main_region_poorIngredient_r2_drinkPoored,
		main_region_expressoDistributed,
		main_region__final_,
		main_region_Ready,
		$NullState$
	};
	
	private final State[] stateVector = new State[3];
	
	private int nextStateIndex;
	
	private ITimer timer;
	
	private final boolean[] timeEvents = new boolean[6];
	
	private BlockingQueue<Runnable> inEventQueue = new LinkedBlockingQueue<Runnable>();
	private boolean isRunningCycle = false;
	public ExpressoStatemachine() {
		sCInterface = new SCInterfaceImpl();
	}
	
	public synchronized void init() {
		this.initialized = true;
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		for (int i = 0; i < 3; i++) {
			stateVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
	}
	
	public synchronized void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		enterSequence_main_region_default();
	}
	
	public synchronized void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		
		if (isRunningCycle) {
			return;
		}
		isRunningCycle = true;
		
		clearOutEvents();
	
		Runnable task = getNextEvent();
		if (task == null) {
			task = getDefaultEvent();
		}
		
		while (task != null) {
			task.run();
			clearEvents();
			task = getNextEvent();
		}
		
		isRunningCycle = false;
	}
	
	protected synchronized void singleCycle() {
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case main_region_PlacingPod_r1_grindcoffee:
				main_region_PlacingPod_r1_grindcoffee_react(true);
				break;
			case main_region_PlacingPod_r1_Ingredient_r1_positionningCup:
				main_region_PlacingPod_r1_Ingredient_r1_positionningCup_react(true);
				break;
			case main_region_PlacingPod_r1_Ingredient_r1_cupPlaced:
				main_region_PlacingPod_r1_Ingredient_r1_cupPlaced_react(true);
				break;
			case main_region_PlacingPod_r1_Ingredient_r2_groundCoffee:
				main_region_PlacingPod_r1_Ingredient_r2_groundCoffee_react(true);
				break;
			case main_region_PlacingPod_r1_Ingredient_r2_coffeeGround:
				main_region_PlacingPod_r1_Ingredient_r2_coffeeGround_react(true);
				break;
			case main_region_PlacingPod_r2_beginHeating:
				main_region_PlacingPod_r2_beginHeating_react(true);
				break;
			case main_region_PlacingPod_r2_IsHot:
				main_region_PlacingPod_r2_IsHot_react(true);
				break;
			case main_region_poorIngredient_r1_poorSugar:
				main_region_poorIngredient_r1_poorSugar_react(true);
				break;
			case main_region_poorIngredient_r1_sugarPoored:
				main_region_poorIngredient_r1_sugarPoored_react(true);
				break;
			case main_region_poorIngredient_r2_poorDrink:
				main_region_poorIngredient_r2_poorDrink_react(true);
				break;
			case main_region_poorIngredient_r2_drinkPoored:
				main_region_poorIngredient_r2_drinkPoored_react(true);
				break;
			case main_region_expressoDistributed:
				main_region_expressoDistributed_react(true);
				break;
			case main_region__final_:
				main_region__final__react(true);
				break;
			case main_region_Ready:
				main_region_Ready_react(true);
				break;
			default:
				// $NullState$
			}
		}
	}
	
	protected Runnable getNextEvent() {
		if(!inEventQueue.isEmpty()) {
			return inEventQueue.poll();
		}
		return null;
	}
	
	protected Runnable getDefaultEvent() {
		return new Runnable() {
			@Override
			public void run() {
				singleCycle();
			}
		};
	}
	
	public synchronized void exit() {
		exitSequence_main_region();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NullState$||stateVector[1] != State.$NullState$||stateVector[2] != State.$NullState$;
	}
	
	/** 
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return (stateVector[0] == State.main_region__final_) && (stateVector[1] == State.$NullState$) && (stateVector[2] == State.$NullState$);
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCInterface.clearEvents();
		for (int i=0; i<timeEvents.length; i++) {
			timeEvents[i] = false;
		}
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
		sCInterface.clearOutEvents();
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case main_region_PlacingPod:
			return stateVector[0].ordinal() >= State.
					main_region_PlacingPod.ordinal()&& stateVector[0].ordinal() <= State.main_region_PlacingPod_r2_IsHot.ordinal();
		case main_region_PlacingPod_r1_grindcoffee:
			return stateVector[0] == State.main_region_PlacingPod_r1_grindcoffee;
		case main_region_PlacingPod_r1_Ingredient:
			return stateVector[0].ordinal() >= State.
					main_region_PlacingPod_r1_Ingredient.ordinal()&& stateVector[0].ordinal() <= State.main_region_PlacingPod_r1_Ingredient_r2_coffeeGround.ordinal();
		case main_region_PlacingPod_r1_Ingredient_r1_positionningCup:
			return stateVector[0] == State.main_region_PlacingPod_r1_Ingredient_r1_positionningCup;
		case main_region_PlacingPod_r1_Ingredient_r1_cupPlaced:
			return stateVector[0] == State.main_region_PlacingPod_r1_Ingredient_r1_cupPlaced;
		case main_region_PlacingPod_r1_Ingredient_r2_groundCoffee:
			return stateVector[1] == State.main_region_PlacingPod_r1_Ingredient_r2_groundCoffee;
		case main_region_PlacingPod_r1_Ingredient_r2_coffeeGround:
			return stateVector[1] == State.main_region_PlacingPod_r1_Ingredient_r2_coffeeGround;
		case main_region_PlacingPod_r2_beginHeating:
			return stateVector[2] == State.main_region_PlacingPod_r2_beginHeating;
		case main_region_PlacingPod_r2_IsHot:
			return stateVector[2] == State.main_region_PlacingPod_r2_IsHot;
		case main_region_poorIngredient:
			return stateVector[0].ordinal() >= State.
					main_region_poorIngredient.ordinal()&& stateVector[0].ordinal() <= State.main_region_poorIngredient_r2_drinkPoored.ordinal();
		case main_region_poorIngredient_r1_poorSugar:
			return stateVector[0] == State.main_region_poorIngredient_r1_poorSugar;
		case main_region_poorIngredient_r1_sugarPoored:
			return stateVector[0] == State.main_region_poorIngredient_r1_sugarPoored;
		case main_region_poorIngredient_r2_poorDrink:
			return stateVector[1] == State.main_region_poorIngredient_r2_poorDrink;
		case main_region_poorIngredient_r2_drinkPoored:
			return stateVector[1] == State.main_region_poorIngredient_r2_drinkPoored;
		case main_region_expressoDistributed:
			return stateVector[0] == State.main_region_expressoDistributed;
		case main_region__final_:
			return stateVector[0] == State.main_region__final_;
		case main_region_Ready:
			return stateVector[0] == State.main_region_Ready;
		default:
			return false;
		}
	}
	
	/**
	* Set the {@link ITimer} for the state machine. It must be set
	* externally on a timed state machine before a run cycle can be correctly
	* executed.
	* 
	* @param timer
	*/
	public synchronized void setTimer(ITimer timer) {
		this.timer = timer;
	}
	
	/**
	* Returns the currently used timer.
	* 
	* @return {@link ITimer}
	*/
	public ITimer getTimer() {
		return timer;
	}
	
	public synchronized void timeElapsed(int eventID) {
		inEventQueue.add(new Runnable() {
			@Override
			public void run() {
				timeEvents[eventID] = true;
				singleCycle();
			}
		});
		runCycle();
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	public synchronized void raiseIsHot() {
		sCInterface.raiseIsHot();
	}
	
	public synchronized void raiseSugarFinishPoored() {
		sCInterface.raiseSugarFinishPoored();
	}
	
	public synchronized void raiseDrinkFinishPoored() {
		sCInterface.raiseDrinkFinishPoored();
	}
	
	public synchronized void raiseDrinkPickedUp() {
		sCInterface.raiseDrinkPickedUp();
	}
	
	public synchronized void raisePrepare() {
		sCInterface.raisePrepare();
	}
	
	public synchronized boolean isRaisedGrindingCoffee() {
		return sCInterface.isRaisedGrindingCoffee();
	}
	
	public synchronized boolean isRaisedGroundingCoffee() {
		return sCInterface.isRaisedGroundingCoffee();
	}
	
	public synchronized boolean isRaisedPlaceCup() {
		return sCInterface.isRaisedPlaceCup();
	}
	
	public synchronized boolean isRaisedHeating() {
		return sCInterface.isRaisedHeating();
	}
	
	public synchronized boolean isRaisedPooringSugar() {
		return sCInterface.isRaisedPooringSugar();
	}
	
	public synchronized boolean isRaisedPooringDrink() {
		return sCInterface.isRaisedPooringDrink();
	}
	
	/* Entry action for state 'grindcoffee'. */
	private void entryAction_main_region_PlacingPod_r1_grindcoffee() {
		timer.setTimer(this, 0, (3 * 1000), false);
		
		sCInterface.raiseGrindingCoffee();
	}
	
	/* Entry action for state 'positionningCup'. */
	private void entryAction_main_region_PlacingPod_r1_Ingredient_r1_positionningCup() {
		timer.setTimer(this, 1, (2 * 1000), false);
		
		sCInterface.raisePlaceCup();
	}
	
	/* Entry action for state 'groundCoffee'. */
	private void entryAction_main_region_PlacingPod_r1_Ingredient_r2_groundCoffee() {
		timer.setTimer(this, 2, (1 * 1000), false);
		
		sCInterface.raiseGroundingCoffee();
	}
	
	/* Entry action for state 'coffeeGround'. */
	private void entryAction_main_region_PlacingPod_r1_Ingredient_r2_coffeeGround() {
		timer.setTimer(this, 3, 100, true);
	}
	
	/* Entry action for state 'IsHot'. */
	private void entryAction_main_region_PlacingPod_r2_IsHot() {
		timer.setTimer(this, 4, 100, true);
	}
	
	/* Entry action for state 'poorSugar'. */
	private void entryAction_main_region_poorIngredient_r1_poorSugar() {
		sCInterface.raisePooringSugar();
	}
	
	/* Entry action for state 'poorDrink'. */
	private void entryAction_main_region_poorIngredient_r2_poorDrink() {
		sCInterface.raisePooringDrink();
	}
	
	/* Entry action for state 'drinkPoored'. */
	private void entryAction_main_region_poorIngredient_r2_drinkPoored() {
		timer.setTimer(this, 5, 100, true);
	}
	
	/* Exit action for state 'grindcoffee'. */
	private void exitAction_main_region_PlacingPod_r1_grindcoffee() {
		timer.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'positionningCup'. */
	private void exitAction_main_region_PlacingPod_r1_Ingredient_r1_positionningCup() {
		timer.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'groundCoffee'. */
	private void exitAction_main_region_PlacingPod_r1_Ingredient_r2_groundCoffee() {
		timer.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'coffeeGround'. */
	private void exitAction_main_region_PlacingPod_r1_Ingredient_r2_coffeeGround() {
		timer.unsetTimer(this, 3);
	}
	
	/* Exit action for state 'IsHot'. */
	private void exitAction_main_region_PlacingPod_r2_IsHot() {
		timer.unsetTimer(this, 4);
	}
	
	/* Exit action for state 'drinkPoored'. */
	private void exitAction_main_region_poorIngredient_r2_drinkPoored() {
		timer.unsetTimer(this, 5);
	}
	
	/* 'default' enter sequence for state PlacingPod */
	private void enterSequence_main_region_PlacingPod_default() {
		enterSequence_main_region_PlacingPod_r1_default();
		enterSequence_main_region_PlacingPod_r2_default();
	}
	
	/* 'default' enter sequence for state grindcoffee */
	private void enterSequence_main_region_PlacingPod_r1_grindcoffee_default() {
		entryAction_main_region_PlacingPod_r1_grindcoffee();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_PlacingPod_r1_grindcoffee;
	}
	
	/* 'default' enter sequence for state Ingredient */
	private void enterSequence_main_region_PlacingPod_r1_Ingredient_default() {
		enterSequence_main_region_PlacingPod_r1_Ingredient_r1_default();
		enterSequence_main_region_PlacingPod_r1_Ingredient_r2_default();
	}
	
	/* 'default' enter sequence for state positionningCup */
	private void enterSequence_main_region_PlacingPod_r1_Ingredient_r1_positionningCup_default() {
		entryAction_main_region_PlacingPod_r1_Ingredient_r1_positionningCup();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_PlacingPod_r1_Ingredient_r1_positionningCup;
	}
	
	/* 'default' enter sequence for state cupPlaced */
	private void enterSequence_main_region_PlacingPod_r1_Ingredient_r1_cupPlaced_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_PlacingPod_r1_Ingredient_r1_cupPlaced;
	}
	
	/* 'default' enter sequence for state groundCoffee */
	private void enterSequence_main_region_PlacingPod_r1_Ingredient_r2_groundCoffee_default() {
		entryAction_main_region_PlacingPod_r1_Ingredient_r2_groundCoffee();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_PlacingPod_r1_Ingredient_r2_groundCoffee;
	}
	
	/* 'default' enter sequence for state coffeeGround */
	private void enterSequence_main_region_PlacingPod_r1_Ingredient_r2_coffeeGround_default() {
		entryAction_main_region_PlacingPod_r1_Ingredient_r2_coffeeGround();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_PlacingPod_r1_Ingredient_r2_coffeeGround;
	}
	
	/* 'default' enter sequence for state beginHeating */
	private void enterSequence_main_region_PlacingPod_r2_beginHeating_default() {
		nextStateIndex = 2;
		stateVector[2] = State.main_region_PlacingPod_r2_beginHeating;
	}
	
	/* 'default' enter sequence for state IsHot */
	private void enterSequence_main_region_PlacingPod_r2_IsHot_default() {
		entryAction_main_region_PlacingPod_r2_IsHot();
		nextStateIndex = 2;
		stateVector[2] = State.main_region_PlacingPod_r2_IsHot;
	}
	
	/* 'default' enter sequence for state poorIngredient */
	private void enterSequence_main_region_poorIngredient_default() {
		enterSequence_main_region_poorIngredient_r1_default();
		enterSequence_main_region_poorIngredient_r2_default();
	}
	
	/* 'default' enter sequence for state poorSugar */
	private void enterSequence_main_region_poorIngredient_r1_poorSugar_default() {
		entryAction_main_region_poorIngredient_r1_poorSugar();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_poorIngredient_r1_poorSugar;
	}
	
	/* 'default' enter sequence for state sugarPoored */
	private void enterSequence_main_region_poorIngredient_r1_sugarPoored_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_poorIngredient_r1_sugarPoored;
	}
	
	/* 'default' enter sequence for state poorDrink */
	private void enterSequence_main_region_poorIngredient_r2_poorDrink_default() {
		entryAction_main_region_poorIngredient_r2_poorDrink();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_poorIngredient_r2_poorDrink;
	}
	
	/* 'default' enter sequence for state drinkPoored */
	private void enterSequence_main_region_poorIngredient_r2_drinkPoored_default() {
		entryAction_main_region_poorIngredient_r2_drinkPoored();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_poorIngredient_r2_drinkPoored;
	}
	
	/* 'default' enter sequence for state expressoDistributed */
	private void enterSequence_main_region_expressoDistributed_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_expressoDistributed;
	}
	
	/* Default enter sequence for state null */
	private void enterSequence_main_region__final__default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region__final_;
	}
	
	/* 'default' enter sequence for state Ready */
	private void enterSequence_main_region_Ready_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Ready;
	}
	
	/* 'default' enter sequence for region main region */
	private void enterSequence_main_region_default() {
		react_main_region__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_PlacingPod_r1_default() {
		react_main_region_PlacingPod_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_PlacingPod_r1_Ingredient_r1_default() {
		react_main_region_PlacingPod_r1_Ingredient_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_main_region_PlacingPod_r1_Ingredient_r2_default() {
		react_main_region_PlacingPod_r1_Ingredient_r2__entry_Default();
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_main_region_PlacingPod_r2_default() {
		react_main_region_PlacingPod_r2__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_poorIngredient_r1_default() {
		react_main_region_poorIngredient_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_main_region_poorIngredient_r2_default() {
		react_main_region_poorIngredient_r2__entry_Default();
	}
	
	/* Default exit sequence for state PlacingPod */
	private void exitSequence_main_region_PlacingPod() {
		exitSequence_main_region_PlacingPod_r1();
		exitSequence_main_region_PlacingPod_r2();
	}
	
	/* Default exit sequence for state grindcoffee */
	private void exitSequence_main_region_PlacingPod_r1_grindcoffee() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_PlacingPod_r1_grindcoffee();
	}
	
	/* Default exit sequence for state Ingredient */
	private void exitSequence_main_region_PlacingPod_r1_Ingredient() {
		exitSequence_main_region_PlacingPod_r1_Ingredient_r1();
		exitSequence_main_region_PlacingPod_r1_Ingredient_r2();
	}
	
	/* Default exit sequence for state positionningCup */
	private void exitSequence_main_region_PlacingPod_r1_Ingredient_r1_positionningCup() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_PlacingPod_r1_Ingredient_r1_positionningCup();
	}
	
	/* Default exit sequence for state cupPlaced */
	private void exitSequence_main_region_PlacingPod_r1_Ingredient_r1_cupPlaced() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state groundCoffee */
	private void exitSequence_main_region_PlacingPod_r1_Ingredient_r2_groundCoffee() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
		
		exitAction_main_region_PlacingPod_r1_Ingredient_r2_groundCoffee();
	}
	
	/* Default exit sequence for state coffeeGround */
	private void exitSequence_main_region_PlacingPod_r1_Ingredient_r2_coffeeGround() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
		
		exitAction_main_region_PlacingPod_r1_Ingredient_r2_coffeeGround();
	}
	
	/* Default exit sequence for state beginHeating */
	private void exitSequence_main_region_PlacingPod_r2_beginHeating() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
	}
	
	/* Default exit sequence for state IsHot */
	private void exitSequence_main_region_PlacingPod_r2_IsHot() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
		
		exitAction_main_region_PlacingPod_r2_IsHot();
	}
	
	/* Default exit sequence for state poorIngredient */
	private void exitSequence_main_region_poorIngredient() {
		exitSequence_main_region_poorIngredient_r1();
		exitSequence_main_region_poorIngredient_r2();
	}
	
	/* Default exit sequence for state poorSugar */
	private void exitSequence_main_region_poorIngredient_r1_poorSugar() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state sugarPoored */
	private void exitSequence_main_region_poorIngredient_r1_sugarPoored() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state poorDrink */
	private void exitSequence_main_region_poorIngredient_r2_poorDrink() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state drinkPoored */
	private void exitSequence_main_region_poorIngredient_r2_drinkPoored() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
		
		exitAction_main_region_poorIngredient_r2_drinkPoored();
	}
	
	/* Default exit sequence for state expressoDistributed */
	private void exitSequence_main_region_expressoDistributed() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for final state. */
	private void exitSequence_main_region__final_() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Ready */
	private void exitSequence_main_region_Ready() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for region main region */
	private void exitSequence_main_region() {
		switch (stateVector[0]) {
		case main_region_PlacingPod_r1_grindcoffee:
			exitSequence_main_region_PlacingPod_r1_grindcoffee();
			break;
		case main_region_PlacingPod_r1_Ingredient_r1_positionningCup:
			exitSequence_main_region_PlacingPod_r1_Ingredient_r1_positionningCup();
			break;
		case main_region_PlacingPod_r1_Ingredient_r1_cupPlaced:
			exitSequence_main_region_PlacingPod_r1_Ingredient_r1_cupPlaced();
			break;
		case main_region_poorIngredient_r1_poorSugar:
			exitSequence_main_region_poorIngredient_r1_poorSugar();
			break;
		case main_region_poorIngredient_r1_sugarPoored:
			exitSequence_main_region_poorIngredient_r1_sugarPoored();
			break;
		case main_region_expressoDistributed:
			exitSequence_main_region_expressoDistributed();
			break;
		case main_region__final_:
			exitSequence_main_region__final_();
			break;
		case main_region_Ready:
			exitSequence_main_region_Ready();
			break;
		default:
			break;
		}
		
		switch (stateVector[1]) {
		case main_region_PlacingPod_r1_Ingredient_r2_groundCoffee:
			exitSequence_main_region_PlacingPod_r1_Ingredient_r2_groundCoffee();
			break;
		case main_region_PlacingPod_r1_Ingredient_r2_coffeeGround:
			exitSequence_main_region_PlacingPod_r1_Ingredient_r2_coffeeGround();
			break;
		case main_region_poorIngredient_r2_poorDrink:
			exitSequence_main_region_poorIngredient_r2_poorDrink();
			break;
		case main_region_poorIngredient_r2_drinkPoored:
			exitSequence_main_region_poorIngredient_r2_drinkPoored();
			break;
		default:
			break;
		}
		
		switch (stateVector[2]) {
		case main_region_PlacingPod_r2_beginHeating:
			exitSequence_main_region_PlacingPod_r2_beginHeating();
			break;
		case main_region_PlacingPod_r2_IsHot:
			exitSequence_main_region_PlacingPod_r2_IsHot();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_main_region_PlacingPod_r1() {
		switch (stateVector[0]) {
		case main_region_PlacingPod_r1_grindcoffee:
			exitSequence_main_region_PlacingPod_r1_grindcoffee();
			break;
		case main_region_PlacingPod_r1_Ingredient_r1_positionningCup:
			exitSequence_main_region_PlacingPod_r1_Ingredient_r1_positionningCup();
			break;
		case main_region_PlacingPod_r1_Ingredient_r1_cupPlaced:
			exitSequence_main_region_PlacingPod_r1_Ingredient_r1_cupPlaced();
			break;
		default:
			break;
		}
		
		switch (stateVector[1]) {
		case main_region_PlacingPod_r1_Ingredient_r2_groundCoffee:
			exitSequence_main_region_PlacingPod_r1_Ingredient_r2_groundCoffee();
			break;
		case main_region_PlacingPod_r1_Ingredient_r2_coffeeGround:
			exitSequence_main_region_PlacingPod_r1_Ingredient_r2_coffeeGround();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_main_region_PlacingPod_r1_Ingredient_r1() {
		switch (stateVector[0]) {
		case main_region_PlacingPod_r1_Ingredient_r1_positionningCup:
			exitSequence_main_region_PlacingPod_r1_Ingredient_r1_positionningCup();
			break;
		case main_region_PlacingPod_r1_Ingredient_r1_cupPlaced:
			exitSequence_main_region_PlacingPod_r1_Ingredient_r1_cupPlaced();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r2 */
	private void exitSequence_main_region_PlacingPod_r1_Ingredient_r2() {
		switch (stateVector[1]) {
		case main_region_PlacingPod_r1_Ingredient_r2_groundCoffee:
			exitSequence_main_region_PlacingPod_r1_Ingredient_r2_groundCoffee();
			break;
		case main_region_PlacingPod_r1_Ingredient_r2_coffeeGround:
			exitSequence_main_region_PlacingPod_r1_Ingredient_r2_coffeeGround();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r2 */
	private void exitSequence_main_region_PlacingPod_r2() {
		switch (stateVector[2]) {
		case main_region_PlacingPod_r2_beginHeating:
			exitSequence_main_region_PlacingPod_r2_beginHeating();
			break;
		case main_region_PlacingPod_r2_IsHot:
			exitSequence_main_region_PlacingPod_r2_IsHot();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_main_region_poorIngredient_r1() {
		switch (stateVector[0]) {
		case main_region_poorIngredient_r1_poorSugar:
			exitSequence_main_region_poorIngredient_r1_poorSugar();
			break;
		case main_region_poorIngredient_r1_sugarPoored:
			exitSequence_main_region_poorIngredient_r1_sugarPoored();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r2 */
	private void exitSequence_main_region_poorIngredient_r2() {
		switch (stateVector[1]) {
		case main_region_poorIngredient_r2_poorDrink:
			exitSequence_main_region_poorIngredient_r2_poorDrink();
			break;
		case main_region_poorIngredient_r2_drinkPoored:
			exitSequence_main_region_poorIngredient_r2_drinkPoored();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region__entry_Default() {
		enterSequence_main_region_Ready_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_PlacingPod_r1__entry_Default() {
		enterSequence_main_region_PlacingPod_r1_grindcoffee_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_PlacingPod_r1_Ingredient_r1__entry_Default() {
		enterSequence_main_region_PlacingPod_r1_Ingredient_r1_positionningCup_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_PlacingPod_r1_Ingredient_r2__entry_Default() {
		enterSequence_main_region_PlacingPod_r1_Ingredient_r2_groundCoffee_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_PlacingPod_r2__entry_Default() {
		enterSequence_main_region_PlacingPod_r2_beginHeating_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_poorIngredient_r1__entry_Default() {
		enterSequence_main_region_poorIngredient_r1_poorSugar_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_poorIngredient_r2__entry_Default() {
		enterSequence_main_region_poorIngredient_r2_poorDrink_default();
	}
	
	/* The reactions of state null. */
	private void react_main_region_PlacingPod_r1__sync0() {
		exitSequence_main_region_PlacingPod();
		react_main_region__sync0();
	}
	
	/* The reactions of state null. */
	private void react_main_region__sync0() {
		enterSequence_main_region_poorIngredient_default();
	}
	
	/* The reactions of state null. */
	private void react_main_region__sync1() {
		enterSequence_main_region_expressoDistributed_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean main_region_PlacingPod_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_PlacingPod_r1_grindcoffee_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[0]) {
				exitSequence_main_region_PlacingPod_r1_grindcoffee();
				enterSequence_main_region_PlacingPod_r1_Ingredient_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_PlacingPod_r1_Ingredient_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		return did_transition;
	}
	
	private boolean main_region_PlacingPod_r1_Ingredient_r1_positionningCup_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[1]) {
				exitSequence_main_region_PlacingPod_r1_Ingredient_r1_positionningCup();
				enterSequence_main_region_PlacingPod_r1_Ingredient_r1_cupPlaced_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_PlacingPod_r1_Ingredient_r1_cupPlaced_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((true && isStateActive(State.main_region_PlacingPod_r1_Ingredient_r2_coffeeGround)) && timeEvents[3])) {
				exitSequence_main_region_PlacingPod_r1_Ingredient();
				react_main_region_PlacingPod_r1__sync0();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_PlacingPod_r1_Ingredient_r2_groundCoffee_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[2]) {
				exitSequence_main_region_PlacingPod_r1_Ingredient_r2_groundCoffee();
				enterSequence_main_region_PlacingPod_r1_Ingredient_r2_coffeeGround_default();
				main_region_PlacingPod_r1_Ingredient_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_PlacingPod_r1_Ingredient_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_PlacingPod_r1_Ingredient_r2_coffeeGround_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((timeEvents[3] && isStateActive(State.main_region_PlacingPod_r1_Ingredient_r1_cupPlaced)) && true)) {
				exitSequence_main_region_PlacingPod_r1_Ingredient();
				react_main_region_PlacingPod_r1__sync0();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_PlacingPod_r1_Ingredient_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_PlacingPod_r2_beginHeating_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.isHot) {
				exitSequence_main_region_PlacingPod_r2_beginHeating();
				enterSequence_main_region_PlacingPod_r2_IsHot_default();
				main_region_PlacingPod_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_PlacingPod_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_PlacingPod_r2_IsHot_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[4]) {
				exitSequence_main_region_PlacingPod();
				react_main_region__sync0();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_PlacingPod_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_poorIngredient_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_poorIngredient_r1_poorSugar_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.sugarFinishPoored) {
				exitSequence_main_region_poorIngredient_r1_poorSugar();
				enterSequence_main_region_poorIngredient_r1_sugarPoored_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_poorIngredient_r1_sugarPoored_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((true && isStateActive(State.main_region_poorIngredient_r2_drinkPoored)) && timeEvents[5])) {
				exitSequence_main_region_poorIngredient();
				react_main_region__sync1();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_poorIngredient_r2_poorDrink_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.drinkFinishPoored) {
				exitSequence_main_region_poorIngredient_r2_poorDrink();
				enterSequence_main_region_poorIngredient_r2_drinkPoored_default();
				main_region_poorIngredient_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_poorIngredient_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_poorIngredient_r2_drinkPoored_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((timeEvents[5] && isStateActive(State.main_region_poorIngredient_r1_sugarPoored)) && true)) {
				exitSequence_main_region_poorIngredient();
				react_main_region__sync1();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_poorIngredient_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_expressoDistributed_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.drinkPickedUp) {
				exitSequence_main_region_expressoDistributed();
				enterSequence_main_region__final__default();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region__final__react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_Ready_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.prepare) {
				exitSequence_main_region_Ready();
				enterSequence_main_region_PlacingPod_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
}
