/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.coffee;

import fr.univcotedazur.polytech.si4.fsm.project.IStatemachine;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface ICoffeeStatemachine extends IStatemachine {
	public interface SCInterface {
	
		public void raisePodIsPlaced();
		
		public void raiseIsHot();
		
		public void raiseCupIsPlaced();
		
		public void raiseSugarFinishPoored();
		
		public void raiseDrinkFinishPoored();
		
		public void raiseDrinkPickedUp();
		
		public boolean isRaisedPlacePod();
		
		public boolean isRaisedPlaceCup();
		
		public boolean isRaisedHeating();
		
		public boolean isRaisedPooringSugar();
		
		public boolean isRaisedPooringDrink();
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onPlacePodRaised();
		public void onPlaceCupRaised();
		public void onHeatingRaised();
		public void onPooringSugarRaised();
		public void onPooringDrinkRaised();
		}
	
	public SCInterface getSCInterface();
	
}
