/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.factory;

import fr.univcotedazur.polytech.si4.fsm.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.project.ITimerCallback;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface IFactoryStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseDoAction();
		
		public void raisePaidNFC();
		
		public void raiseSelected();
		
		public void raiseAddCoin();
		
		public void raiseCancel();
		
		public void raiseIsPaid();
		
		public void raiseMoneyBack();
		
		public void raiseRefunded();
		
		public boolean isRaisedDoRefund();
		
		public boolean isRaisedDoRestart();
		
		public boolean isRaisedDoPaymentByNFC();
		
		public boolean isRaisedDoBackCoin();
		
		public boolean isRaisedDoMoneyBack();
		
		public boolean isRaisedDoStartPreparation();
		
		public boolean isRaisedDoSelection();
		
		public boolean isRaisedAddedCoin();
		
		public long getCoin();
		
		public void setCoin(long value);
		
		public String getSelection();
		
		public void setSelection(String value);
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onDoRefundRaised();
		public void onDoRestartRaised();
		public void onDoPaymentByNFCRaised();
		public void onDoBackCoinRaised();
		public void onDoMoneyBackRaised();
		public void onDoStartPreparationRaised();
		public void onDoSelectionRaised();
		public void onAddedCoinRaised();
		}
	
	public SCInterface getSCInterface();
	
}
