/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.soup;

import fr.univcotedazur.polytech.si4.fsm.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.project.ITimerCallback;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface ISoupStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseDrinkPickedUp();
		
		public void raiseSpiceFinishPoored();
		
		public void raisePrepare();
		
		public boolean isRaisedPlaceCup();
		
		public boolean isRaisedPreparationFinished();
		
		public boolean isRaisedAddingBread();
		
		public boolean getOptionBread();
		
		public void setOptionBread(boolean value);
		
		public long getBreadTime();
		
		public void setBreadTime(long value);
		
		public long getTimePoorDrink();
		
		public void setTimePoorDrink(long value);
		
		public boolean getUserCup();
		
		public void setUserCup(boolean value);
		
		public long getTimeToHeating();
		
		public void setTimeToHeating(long value);
		
		public long getTimeToPooringSpices();
		
		public void setTimeToPooringSpices(long value);
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onPlaceCupRaised();
		public void onPreparationFinishedRaised();
		public void onAddingBreadRaised();
		}
	
	public SCInterface getSCInterface();
	
}
