/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.soup;

import fr.univcotedazur.polytech.si4.fsm.project.ITimer;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public class SoupStatemachine implements ISoupStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private List<SCInterfaceListener> listeners = new LinkedList<SCInterfaceListener>();
		
		public List<SCInterfaceListener> getListeners() {
			return listeners;
		}
		private boolean isHot;
		
		
		public void raiseIsHot() {
			synchronized(SoupStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							isHot = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean drinkFinishPoored;
		
		
		public void raiseDrinkFinishPoored() {
			synchronized(SoupStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							drinkFinishPoored = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean drinkPickedUp;
		
		
		public void raiseDrinkPickedUp() {
			synchronized(SoupStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							drinkPickedUp = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean spiceFinishPoored;
		
		
		public void raiseSpiceFinishPoored() {
			synchronized(SoupStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							spiceFinishPoored = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean prepare;
		
		
		public void raisePrepare() {
			synchronized(SoupStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							prepare = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean placeCup;
		
		
		public boolean isRaisedPlaceCup() {
			synchronized(SoupStatemachine.this) {
				return placeCup;
			}
		}
		
		protected void raisePlaceCup() {
			synchronized(SoupStatemachine.this) {
				placeCup = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPlaceCupRaised();
				}
			}
		}
		
		private boolean heating;
		
		
		public boolean isRaisedHeating() {
			synchronized(SoupStatemachine.this) {
				return heating;
			}
		}
		
		protected void raiseHeating() {
			synchronized(SoupStatemachine.this) {
				heating = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onHeatingRaised();
				}
			}
		}
		
		private boolean pooringDrink;
		
		
		public boolean isRaisedPooringDrink() {
			synchronized(SoupStatemachine.this) {
				return pooringDrink;
			}
		}
		
		protected void raisePooringDrink() {
			synchronized(SoupStatemachine.this) {
				pooringDrink = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPooringDrinkRaised();
				}
			}
		}
		
		private boolean preparationFinished;
		
		
		public boolean isRaisedPreparationFinished() {
			synchronized(SoupStatemachine.this) {
				return preparationFinished;
			}
		}
		
		protected void raisePreparationFinished() {
			synchronized(SoupStatemachine.this) {
				preparationFinished = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPreparationFinishedRaised();
				}
			}
		}
		
		private boolean pooringSpice;
		
		
		public boolean isRaisedPooringSpice() {
			synchronized(SoupStatemachine.this) {
				return pooringSpice;
			}
		}
		
		protected void raisePooringSpice() {
			synchronized(SoupStatemachine.this) {
				pooringSpice = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPooringSpiceRaised();
				}
			}
		}
		
		protected void clearEvents() {
			isHot = false;
			drinkFinishPoored = false;
			drinkPickedUp = false;
			spiceFinishPoored = false;
			prepare = false;
		}
		protected void clearOutEvents() {
		
		placeCup = false;
		heating = false;
		pooringDrink = false;
		preparationFinished = false;
		pooringSpice = false;
		}
		
	}
	
	
	protected SCInterfaceImpl sCInterface;
	
	private boolean initialized = false;
	
	public enum State {
		main_region_preparationIngredient,
		main_region_preparationIngredient_r1_positionningCup,
		main_region_preparationIngredient_r1_cupPositionned,
		main_region_preparationIngredient_r1_poorIngredient,
		main_region_preparationIngredient_r1_poorIngredient_r1_getSoup,
		main_region_preparationIngredient_r1_poorIngredient_r1_addSoup,
		main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice,
		main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored,
		main_region_preparationIngredient_r2_beginHeating,
		main_region_preparationIngredient_r2_IsHot,
		main_region_DrinkDistribute,
		main_region_poorDrink,
		main_region_Ready,
		$NullState$
	};
	
	private final State[] stateVector = new State[3];
	
	private int nextStateIndex;
	
	private ITimer timer;
	
	private final boolean[] timeEvents = new boolean[5];
	
	private BlockingQueue<Runnable> inEventQueue = new LinkedBlockingQueue<Runnable>();
	private boolean isRunningCycle = false;
	public SoupStatemachine() {
		sCInterface = new SCInterfaceImpl();
	}
	
	public synchronized void init() {
		this.initialized = true;
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		for (int i = 0; i < 3; i++) {
			stateVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
	}
	
	public synchronized void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		enterSequence_main_region_default();
	}
	
	public synchronized void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		
		if (isRunningCycle) {
			return;
		}
		isRunningCycle = true;
		
		clearOutEvents();
	
		Runnable task = getNextEvent();
		if (task == null) {
			task = getDefaultEvent();
		}
		
		while (task != null) {
			task.run();
			clearEvents();
			task = getNextEvent();
		}
		
		isRunningCycle = false;
	}
	
	protected synchronized void singleCycle() {
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case main_region_preparationIngredient_r1_positionningCup:
				main_region_preparationIngredient_r1_positionningCup_react(true);
				break;
			case main_region_preparationIngredient_r1_cupPositionned:
				main_region_preparationIngredient_r1_cupPositionned_react(true);
				break;
			case main_region_preparationIngredient_r1_poorIngredient_r1_getSoup:
				main_region_preparationIngredient_r1_poorIngredient_r1_getSoup_react(true);
				break;
			case main_region_preparationIngredient_r1_poorIngredient_r1_addSoup:
				main_region_preparationIngredient_r1_poorIngredient_r1_addSoup_react(true);
				break;
			case main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice:
				main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice_react(true);
				break;
			case main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored:
				main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored_react(true);
				break;
			case main_region_preparationIngredient_r2_beginHeating:
				main_region_preparationIngredient_r2_beginHeating_react(true);
				break;
			case main_region_preparationIngredient_r2_IsHot:
				main_region_preparationIngredient_r2_IsHot_react(true);
				break;
			case main_region_DrinkDistribute:
				main_region_DrinkDistribute_react(true);
				break;
			case main_region_poorDrink:
				main_region_poorDrink_react(true);
				break;
			case main_region_Ready:
				main_region_Ready_react(true);
				break;
			default:
				// $NullState$
			}
		}
	}
	
	protected Runnable getNextEvent() {
		if(!inEventQueue.isEmpty()) {
			return inEventQueue.poll();
		}
		return null;
	}
	
	protected Runnable getDefaultEvent() {
		return new Runnable() {
			@Override
			public void run() {
				singleCycle();
			}
		};
	}
	
	public synchronized void exit() {
		exitSequence_main_region();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NullState$||stateVector[1] != State.$NullState$||stateVector[2] != State.$NullState$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return false;
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCInterface.clearEvents();
		for (int i=0; i<timeEvents.length; i++) {
			timeEvents[i] = false;
		}
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
		sCInterface.clearOutEvents();
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case main_region_preparationIngredient:
			return stateVector[0].ordinal() >= State.
					main_region_preparationIngredient.ordinal()&& stateVector[0].ordinal() <= State.main_region_preparationIngredient_r2_IsHot.ordinal();
		case main_region_preparationIngredient_r1_positionningCup:
			return stateVector[0] == State.main_region_preparationIngredient_r1_positionningCup;
		case main_region_preparationIngredient_r1_cupPositionned:
			return stateVector[0] == State.main_region_preparationIngredient_r1_cupPositionned;
		case main_region_preparationIngredient_r1_poorIngredient:
			return stateVector[0].ordinal() >= State.
					main_region_preparationIngredient_r1_poorIngredient.ordinal()&& stateVector[0].ordinal() <= State.main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored.ordinal();
		case main_region_preparationIngredient_r1_poorIngredient_r1_getSoup:
			return stateVector[0] == State.main_region_preparationIngredient_r1_poorIngredient_r1_getSoup;
		case main_region_preparationIngredient_r1_poorIngredient_r1_addSoup:
			return stateVector[0] == State.main_region_preparationIngredient_r1_poorIngredient_r1_addSoup;
		case main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice:
			return stateVector[1] == State.main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice;
		case main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored:
			return stateVector[1] == State.main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored;
		case main_region_preparationIngredient_r2_beginHeating:
			return stateVector[2] == State.main_region_preparationIngredient_r2_beginHeating;
		case main_region_preparationIngredient_r2_IsHot:
			return stateVector[2] == State.main_region_preparationIngredient_r2_IsHot;
		case main_region_DrinkDistribute:
			return stateVector[0] == State.main_region_DrinkDistribute;
		case main_region_poorDrink:
			return stateVector[0] == State.main_region_poorDrink;
		case main_region_Ready:
			return stateVector[0] == State.main_region_Ready;
		default:
			return false;
		}
	}
	
	/**
	* Set the {@link ITimer} for the state machine. It must be set
	* externally on a timed state machine before a run cycle can be correctly
	* executed.
	* 
	* @param timer
	*/
	public synchronized void setTimer(ITimer timer) {
		this.timer = timer;
	}
	
	/**
	* Returns the currently used timer.
	* 
	* @return {@link ITimer}
	*/
	public ITimer getTimer() {
		return timer;
	}
	
	public synchronized void timeElapsed(int eventID) {
		inEventQueue.add(new Runnable() {
			@Override
			public void run() {
				timeEvents[eventID] = true;
				singleCycle();
			}
		});
		runCycle();
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	public synchronized void raiseIsHot() {
		sCInterface.raiseIsHot();
	}
	
	public synchronized void raiseDrinkFinishPoored() {
		sCInterface.raiseDrinkFinishPoored();
	}
	
	public synchronized void raiseDrinkPickedUp() {
		sCInterface.raiseDrinkPickedUp();
	}
	
	public synchronized void raiseSpiceFinishPoored() {
		sCInterface.raiseSpiceFinishPoored();
	}
	
	public synchronized void raisePrepare() {
		sCInterface.raisePrepare();
	}
	
	public synchronized boolean isRaisedPlaceCup() {
		return sCInterface.isRaisedPlaceCup();
	}
	
	public synchronized boolean isRaisedHeating() {
		return sCInterface.isRaisedHeating();
	}
	
	public synchronized boolean isRaisedPooringDrink() {
		return sCInterface.isRaisedPooringDrink();
	}
	
	public synchronized boolean isRaisedPreparationFinished() {
		return sCInterface.isRaisedPreparationFinished();
	}
	
	public synchronized boolean isRaisedPooringSpice() {
		return sCInterface.isRaisedPooringSpice();
	}
	
	/* Entry action for state 'positionningCup'. */
	private void entryAction_main_region_preparationIngredient_r1_positionningCup() {
		timer.setTimer(this, 0, (2 * 1000), false);
		
		sCInterface.raisePlaceCup();
	}
	
	/* Entry action for state 'getSoup'. */
	private void entryAction_main_region_preparationIngredient_r1_poorIngredient_r1_getSoup() {
		timer.setTimer(this, 1, (2 * 1000), false);
	}
	
	/* Entry action for state 'poorSpice'. */
	private void entryAction_main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice() {
		sCInterface.raisePooringSpice();
	}
	
	/* Entry action for state 'spicePoored'. */
	private void entryAction_main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored() {
		timer.setTimer(this, 2, 10, true);
	}
	
	/* Entry action for state 'beginHeating'. */
	private void entryAction_main_region_preparationIngredient_r2_beginHeating() {
		sCInterface.raiseHeating();
	}
	
	/* Entry action for state 'IsHot'. */
	private void entryAction_main_region_preparationIngredient_r2_IsHot() {
		timer.setTimer(this, 3, 100, true);
	}
	
	/* Entry action for state 'DrinkDistribute'. */
	private void entryAction_main_region_DrinkDistribute() {
		timer.setTimer(this, 4, 100, false);
		
		sCInterface.raisePreparationFinished();
	}
	
	/* Entry action for state 'poorDrink'. */
	private void entryAction_main_region_poorDrink() {
		sCInterface.raisePooringDrink();
	}
	
	/* Exit action for state 'positionningCup'. */
	private void exitAction_main_region_preparationIngredient_r1_positionningCup() {
		timer.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'getSoup'. */
	private void exitAction_main_region_preparationIngredient_r1_poorIngredient_r1_getSoup() {
		timer.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'spicePoored'. */
	private void exitAction_main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored() {
		timer.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'IsHot'. */
	private void exitAction_main_region_preparationIngredient_r2_IsHot() {
		timer.unsetTimer(this, 3);
	}
	
	/* Exit action for state 'DrinkDistribute'. */
	private void exitAction_main_region_DrinkDistribute() {
		timer.unsetTimer(this, 4);
	}
	
	/* 'default' enter sequence for state preparationIngredient */
	private void enterSequence_main_region_preparationIngredient_default() {
		enterSequence_main_region_preparationIngredient_r1_default();
		enterSequence_main_region_preparationIngredient_r2_default();
	}
	
	/* 'default' enter sequence for state positionningCup */
	private void enterSequence_main_region_preparationIngredient_r1_positionningCup_default() {
		entryAction_main_region_preparationIngredient_r1_positionningCup();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_preparationIngredient_r1_positionningCup;
	}
	
	/* 'default' enter sequence for state cupPositionned */
	private void enterSequence_main_region_preparationIngredient_r1_cupPositionned_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_preparationIngredient_r1_cupPositionned;
	}
	
	/* 'default' enter sequence for state poorIngredient */
	private void enterSequence_main_region_preparationIngredient_r1_poorIngredient_default() {
		enterSequence_main_region_preparationIngredient_r1_poorIngredient_r1_default();
		enterSequence_main_region_preparationIngredient_r1_poorIngredient_r2_default();
	}
	
	/* 'default' enter sequence for state getSoup */
	private void enterSequence_main_region_preparationIngredient_r1_poorIngredient_r1_getSoup_default() {
		entryAction_main_region_preparationIngredient_r1_poorIngredient_r1_getSoup();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_preparationIngredient_r1_poorIngredient_r1_getSoup;
	}
	
	/* 'default' enter sequence for state addSoup */
	private void enterSequence_main_region_preparationIngredient_r1_poorIngredient_r1_addSoup_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_preparationIngredient_r1_poorIngredient_r1_addSoup;
	}
	
	/* 'default' enter sequence for state poorSpice */
	private void enterSequence_main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice_default() {
		entryAction_main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice;
	}
	
	/* 'default' enter sequence for state spicePoored */
	private void enterSequence_main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored_default() {
		entryAction_main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored;
	}
	
	/* 'default' enter sequence for state beginHeating */
	private void enterSequence_main_region_preparationIngredient_r2_beginHeating_default() {
		entryAction_main_region_preparationIngredient_r2_beginHeating();
		nextStateIndex = 2;
		stateVector[2] = State.main_region_preparationIngredient_r2_beginHeating;
	}
	
	/* 'default' enter sequence for state IsHot */
	private void enterSequence_main_region_preparationIngredient_r2_IsHot_default() {
		entryAction_main_region_preparationIngredient_r2_IsHot();
		nextStateIndex = 2;
		stateVector[2] = State.main_region_preparationIngredient_r2_IsHot;
	}
	
	/* 'default' enter sequence for state DrinkDistribute */
	private void enterSequence_main_region_DrinkDistribute_default() {
		entryAction_main_region_DrinkDistribute();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_DrinkDistribute;
	}
	
	/* 'default' enter sequence for state poorDrink */
	private void enterSequence_main_region_poorDrink_default() {
		entryAction_main_region_poorDrink();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_poorDrink;
	}
	
	/* 'default' enter sequence for state Ready */
	private void enterSequence_main_region_Ready_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Ready;
	}
	
	/* 'default' enter sequence for region main region */
	private void enterSequence_main_region_default() {
		react_main_region__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_preparationIngredient_r1_default() {
		react_main_region_preparationIngredient_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_preparationIngredient_r1_poorIngredient_r1_default() {
		react_main_region_preparationIngredient_r1_poorIngredient_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_main_region_preparationIngredient_r1_poorIngredient_r2_default() {
		react_main_region_preparationIngredient_r1_poorIngredient_r2__entry_Default();
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_main_region_preparationIngredient_r2_default() {
		react_main_region_preparationIngredient_r2__entry_Default();
	}
	
	/* Default exit sequence for state preparationIngredient */
	private void exitSequence_main_region_preparationIngredient() {
		exitSequence_main_region_preparationIngredient_r1();
		exitSequence_main_region_preparationIngredient_r2();
	}
	
	/* Default exit sequence for state positionningCup */
	private void exitSequence_main_region_preparationIngredient_r1_positionningCup() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_preparationIngredient_r1_positionningCup();
	}
	
	/* Default exit sequence for state cupPositionned */
	private void exitSequence_main_region_preparationIngredient_r1_cupPositionned() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state poorIngredient */
	private void exitSequence_main_region_preparationIngredient_r1_poorIngredient() {
		exitSequence_main_region_preparationIngredient_r1_poorIngredient_r1();
		exitSequence_main_region_preparationIngredient_r1_poorIngredient_r2();
	}
	
	/* Default exit sequence for state getSoup */
	private void exitSequence_main_region_preparationIngredient_r1_poorIngredient_r1_getSoup() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_preparationIngredient_r1_poorIngredient_r1_getSoup();
	}
	
	/* Default exit sequence for state addSoup */
	private void exitSequence_main_region_preparationIngredient_r1_poorIngredient_r1_addSoup() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state poorSpice */
	private void exitSequence_main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state spicePoored */
	private void exitSequence_main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
		
		exitAction_main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored();
	}
	
	/* Default exit sequence for state beginHeating */
	private void exitSequence_main_region_preparationIngredient_r2_beginHeating() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
	}
	
	/* Default exit sequence for state IsHot */
	private void exitSequence_main_region_preparationIngredient_r2_IsHot() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
		
		exitAction_main_region_preparationIngredient_r2_IsHot();
	}
	
	/* Default exit sequence for state DrinkDistribute */
	private void exitSequence_main_region_DrinkDistribute() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_DrinkDistribute();
	}
	
	/* Default exit sequence for state poorDrink */
	private void exitSequence_main_region_poorDrink() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Ready */
	private void exitSequence_main_region_Ready() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for region main region */
	private void exitSequence_main_region() {
		switch (stateVector[0]) {
		case main_region_preparationIngredient_r1_positionningCup:
			exitSequence_main_region_preparationIngredient_r1_positionningCup();
			break;
		case main_region_preparationIngredient_r1_cupPositionned:
			exitSequence_main_region_preparationIngredient_r1_cupPositionned();
			break;
		case main_region_preparationIngredient_r1_poorIngredient_r1_getSoup:
			exitSequence_main_region_preparationIngredient_r1_poorIngredient_r1_getSoup();
			break;
		case main_region_preparationIngredient_r1_poorIngredient_r1_addSoup:
			exitSequence_main_region_preparationIngredient_r1_poorIngredient_r1_addSoup();
			break;
		case main_region_DrinkDistribute:
			exitSequence_main_region_DrinkDistribute();
			break;
		case main_region_poorDrink:
			exitSequence_main_region_poorDrink();
			break;
		case main_region_Ready:
			exitSequence_main_region_Ready();
			break;
		default:
			break;
		}
		
		switch (stateVector[1]) {
		case main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice:
			exitSequence_main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice();
			break;
		case main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored:
			exitSequence_main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored();
			break;
		default:
			break;
		}
		
		switch (stateVector[2]) {
		case main_region_preparationIngredient_r2_beginHeating:
			exitSequence_main_region_preparationIngredient_r2_beginHeating();
			break;
		case main_region_preparationIngredient_r2_IsHot:
			exitSequence_main_region_preparationIngredient_r2_IsHot();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_main_region_preparationIngredient_r1() {
		switch (stateVector[0]) {
		case main_region_preparationIngredient_r1_positionningCup:
			exitSequence_main_region_preparationIngredient_r1_positionningCup();
			break;
		case main_region_preparationIngredient_r1_cupPositionned:
			exitSequence_main_region_preparationIngredient_r1_cupPositionned();
			break;
		case main_region_preparationIngredient_r1_poorIngredient_r1_getSoup:
			exitSequence_main_region_preparationIngredient_r1_poorIngredient_r1_getSoup();
			break;
		case main_region_preparationIngredient_r1_poorIngredient_r1_addSoup:
			exitSequence_main_region_preparationIngredient_r1_poorIngredient_r1_addSoup();
			break;
		default:
			break;
		}
		
		switch (stateVector[1]) {
		case main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice:
			exitSequence_main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice();
			break;
		case main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored:
			exitSequence_main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_main_region_preparationIngredient_r1_poorIngredient_r1() {
		switch (stateVector[0]) {
		case main_region_preparationIngredient_r1_poorIngredient_r1_getSoup:
			exitSequence_main_region_preparationIngredient_r1_poorIngredient_r1_getSoup();
			break;
		case main_region_preparationIngredient_r1_poorIngredient_r1_addSoup:
			exitSequence_main_region_preparationIngredient_r1_poorIngredient_r1_addSoup();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r2 */
	private void exitSequence_main_region_preparationIngredient_r1_poorIngredient_r2() {
		switch (stateVector[1]) {
		case main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice:
			exitSequence_main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice();
			break;
		case main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored:
			exitSequence_main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r2 */
	private void exitSequence_main_region_preparationIngredient_r2() {
		switch (stateVector[2]) {
		case main_region_preparationIngredient_r2_beginHeating:
			exitSequence_main_region_preparationIngredient_r2_beginHeating();
			break;
		case main_region_preparationIngredient_r2_IsHot:
			exitSequence_main_region_preparationIngredient_r2_IsHot();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_preparationIngredient_r1__entry_Default() {
		enterSequence_main_region_preparationIngredient_r1_positionningCup_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_preparationIngredient_r1_poorIngredient_r1__entry_Default() {
		enterSequence_main_region_preparationIngredient_r1_poorIngredient_r1_getSoup_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_preparationIngredient_r1_poorIngredient_r2__entry_Default() {
		enterSequence_main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_preparationIngredient_r2__entry_Default() {
		enterSequence_main_region_preparationIngredient_r2_beginHeating_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region__entry_Default() {
		enterSequence_main_region_Ready_default();
	}
	
	/* The reactions of state null. */
	private void react_main_region_preparationIngredient_r1__sync0() {
		exitSequence_main_region_preparationIngredient();
		react_main_region__sync0();
	}
	
	/* The reactions of state null. */
	private void react_main_region__sync0() {
		enterSequence_main_region_poorDrink_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean main_region_preparationIngredient_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_preparationIngredient_r1_positionningCup_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[0]) {
				exitSequence_main_region_preparationIngredient_r1_positionningCup();
				enterSequence_main_region_preparationIngredient_r1_cupPositionned_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_preparationIngredient_r1_cupPositionned_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			exitSequence_main_region_preparationIngredient_r1_cupPositionned();
			enterSequence_main_region_preparationIngredient_r1_poorIngredient_default();
		}
		return did_transition;
	}
	
	private boolean main_region_preparationIngredient_r1_poorIngredient_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		return did_transition;
	}
	
	private boolean main_region_preparationIngredient_r1_poorIngredient_r1_getSoup_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[1]) {
				exitSequence_main_region_preparationIngredient_r1_poorIngredient_r1_getSoup();
				enterSequence_main_region_preparationIngredient_r1_poorIngredient_r1_addSoup_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_preparationIngredient_r1_poorIngredient_r1_addSoup_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((true && isStateActive(State.main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored)) && timeEvents[2])) {
				exitSequence_main_region_preparationIngredient_r1_poorIngredient();
				react_main_region_preparationIngredient_r1__sync0();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.spiceFinishPoored) {
				exitSequence_main_region_preparationIngredient_r1_poorIngredient_r2_poorSpice();
				enterSequence_main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored_default();
				main_region_preparationIngredient_r1_poorIngredient_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_preparationIngredient_r1_poorIngredient_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_preparationIngredient_r1_poorIngredient_r2_spicePoored_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((timeEvents[2] && isStateActive(State.main_region_preparationIngredient_r1_poorIngredient_r1_addSoup)) && true)) {
				exitSequence_main_region_preparationIngredient_r1_poorIngredient();
				react_main_region_preparationIngredient_r1__sync0();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_preparationIngredient_r1_poorIngredient_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_preparationIngredient_r2_beginHeating_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.isHot) {
				exitSequence_main_region_preparationIngredient_r2_beginHeating();
				enterSequence_main_region_preparationIngredient_r2_IsHot_default();
				main_region_preparationIngredient_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_preparationIngredient_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_preparationIngredient_r2_IsHot_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[3]) {
				exitSequence_main_region_preparationIngredient();
				react_main_region__sync0();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_preparationIngredient_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_DrinkDistribute_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[4]) {
				exitSequence_main_region_DrinkDistribute();
				enterSequence_main_region_Ready_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_poorDrink_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.drinkFinishPoored) {
				exitSequence_main_region_poorDrink();
				enterSequence_main_region_DrinkDistribute_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_Ready_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.prepare) {
				exitSequence_main_region_Ready();
				enterSequence_main_region_preparationIngredient_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
}
